### ISSUE TITLE
[Bug] Dropdown component listener removal issue

### ISSUE THREAD

**Issue by jungleBadger** [carbon-design-system/carbon-components-vue#1004]
## Detailed description

> Describe in detail the issue you're having.

After adding a `<cv-dropdown>` component and hiding it with v-if/changing route with vue-router, there is a listener attached to `window` that keeps trying to close the dropdown, but as it doesn't exists any longer the function fails.

> Is this a feature request (new component, new icon), a bug, or a general issue?

Bug

> Is this issue related to a specific component?

Dropdown

> What did you expect to happen? What happened instead? What would you like to see changed?

After removing the cvdropdown component, I expect the listener to be removed as well.

> What browser are you working in?

Version 85.0.4183.83 (Official Build) (64-bit)

> What version of the Carbon Design System are you using?

"@carbon/vue": "^2.31.1",

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

N/A

## Steps to reproduce the issue

1. Go to a page with a cv-dropdown-component rendered
2. Hide this component with v-if or using vue-router
3. Click in the screen looking the console.log error

## Additional information

This can be reproduced in the vue story book: https://vue.carbondesignsystem.com/?path=/story/components-cvdropdown--default

![demoissue](https://user-images.githubusercontent.com/12788435/92271220-ccc65100-eebd-11ea-8ad3-41fb557e1712.gif)

**Comment by lee-chase** [comment]
Published in 2.32.0-canary.0

Will graduate if to 2.32.0 tomorrow if possible.

**Comment by jungleBadger** [comment]
Hey @lee-chase even though we moved the cleanup process to the `beforeDestroy` handler, the issue still can be observed in version `12.32.0`

The issue can be replicated in storybook: https://vue.carbondesignsystem.com/?path=/story/components-cvdropdown--slots


1. Open chrome inspector console
2. Open the dropdown and select an option
3. Navigate to another component doc through the left panel

**Comment by lee-chase** [comment]
@jungleBadger try the latest canary. Switched to using a directive which seems more reliable, I do not understand why.

**Comment by jungleBadger** [comment]
> @jungleBadger try the latest canary. Switched to using a directive which seems more reliable, I do not understand why.

I tested with version `2.33.0-canary.0` and it works fine now. Thank you!
