### ISSUE TITLE
A label for expand/collapse row buttons in cv-data-table

### ISSUE THREAD

**Issue by nick-somebody** [carbon-design-system/carbon-components-vue#1006]
**Is your feature request related to a problem? Please describe.**
https://github.com/carbon-design-system/carbon-components-vue/blob/c3afb6692aa1f98d6cf19829638c22d5e91da48a/packages/core/src/components/cv-data-table/_cv-data-table-row-inner.vue#L11
Since the expand row button on the data table component is an icon only, it needs an `aria-label` or some other label available to an accessible API.

**Describe the solution you'd like**
A name for the expand/collapse button that is in the accessibility tree.

**Describe alternatives you've considered**
A prop with a default at `cv-data-table` level that gets passed up through the components to where it's needed (the `cv-data-table-row-inner` component). This would help people needing to support other languages.

**Additional context**
I would be happy to help add this.

**Comment by lee-chase** [comment]
Published in 2.32.0-canary.0

Will graduate if to 2.32.0 tomorrow if possible.
