### ISSUE TITLE
[uidMixin] - Pulls "id" out of $attrs, preventing "id" being set in that component's base element

### ISSUE THREAD

**Issue by nick-somebody** [carbon-design-system/carbon-components-vue#1007]
**Is your feature request related to a problem? Please describe.**
https://github.com/carbon-design-system/carbon-components-vue/blob/master/packages/core/src/mixins/uid-mixin.js
Adding an `id` prop to every component means an `id` attribute cannot be assigned to the base element of that component.

eg. https://github.com/carbon-design-system/carbon-components-vue/blob/master/packages/core/src/components/cv-data-table/cv-data-table-heading.vue
I want to assign an id to the table header so that I can reference the header from other cells, I cannot do this without writing my own header component.

**Describe the solution you'd like**
Should read the `id` value of the `$attrs` collection, so it remains there.

**Describe alternatives you've considered**
Any component that uses `uidMixin` is used, should also apply the `id` value to the base element.

**Comment by lee-chase** [comment]
It's not really possible to do that as some components make use of the id where supplied for other elements that need an ID such as text-input and where we want the user to be able to override it. 

https://github.com/carbon-design-system/carbon-components-vue/blob/master/packages/core/src/components/cv-text-input/cv-text-input.vue

Viable options, without making breaking changes, are to

1. Where a component does not otherwise use the ID as an ID add it to the top level element.
2. Add an id of the form `${uid}--container` or similar to the top level element.

When you say you want to reference it from other cells, can you explain what you are trying to achieve? There may be another mechanism to achieve what you are trying to accomplish.

**Comment by nick-somebody** [comment]
Well, it's basically for a11y reasons.

Our particular use is to add a grouping row into the grid, this is not difficult to do. But the thing is, technically that grouping row is a header for all the cells within it's group and column span, in order to make this semantically sensible, we should use the `headers` attribute to link the cells to both headers.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/td

I've found a workaround for now.

I might be explaining my suggested fix poorly though. From the looks, and this could be wrong, your components make use of `uid` internally and doesn't need reactivity. I might need to do a better search of code but...

Change the `uid` computed property to something like:
```js
return this.$attrs?.id?.length ? this.$attrs.id : idGen.newId();
```
Then dump the `props` definition on the mixin.

My current limited understanding looks like that change doesn't collide with code you linked but I am new to this lib, so I might be missing a lot of other details.

**Comment by lee-chase** [comment]
Unfortunately,  that would break cv-text-input as both the containing <div> and <input> would get the same ID.

Just about to publish a canary which will add the ID onto the outer element of components that do not otherwise use the ID. I'll tag this issue.

**Comment by lee-chase** [comment]
Published in 2.32.0-canary.0

Will graduate if to 2.32.0 tomorrow if possible.

**Comment by nick-somebody** [comment]
I take your above mentioned point about the colliding `id`s, sorry I did not read your first message correctly.

Your PR does appear to address the issue, I will try the canary release you have done.

We are doing a quick fire project at the moment, so I really appreciate that you've been able to assist so quickly. There may be more in future, I would be happy to contribute fixes if you're open to it.

**Comment by lee-chase** [comment]
Always open to contributions @nick-somebody
