### ISSUE TITLE
Text align for columns in CvDataTable does not work anymore

### ISSUE THREAD

**Issue by KJaspers** [carbon-design-system/carbon-components-vue#1019]
Using textAlign in the headingStyle does not work anymore, e.g. the PORT column in the storybook is no longer right aligned: http://vue.carbondesignsystem.com/?path=/story/components-cvdatatable--styled-columns

**Comment by lee-chase** [comment]
This appears to be due to a change in the styling of the bx--table-header-label in core carbon. You can revert that by using 'display: block' or use 'float: right' instead.

**Comment by schuetza** [comment]
See https://github.com/carbon-design-system/carbon-components-vue/issues/1252. 
Issue is that the headingStyle is nor applied correctly to the `<th>`

**Comment by schuetza** [comment]
From my point of view, you might close this in favor of #1252.
