### ISSUE TITLE
Vue 3 changes support for array refs

### ISSUE THREAD

**Issue by lee-chase** [carbon-design-system/carbon-components-vue#1021]
Review existing code and raise issues labelled 'V3 - Vue 3'

Support for array refs has changed 
https://v3.vuejs.org/guide/migration/array-refs.html

This affects

- [ ] Combobox options
- [ ] Data table rows CvDataTable
- [ ] Progress steps CvProgress
- [ ] links in CvTabs?

Possibly more

**Comment by davidnixon** [comment]
@lee-chase closing as stale.  Hope that's OK.
