### ISSUE TITLE
UI shell header components have various problems.

### ISSUE THREAD

**Issue by barbarahartel** [carbon-design-system/carbon-components-vue#1030]
**Versions used:**
"dependencies": {
    "@carbon/vue": "2.30.2",
    "chart.js": "2.9.3",
    "core-js": "3.6.5",
    "file-saver": "2.0.2",
    "jquery": "3.5.1",
    "jquery-ui": "1.12.1",
    "jquery-ui-dist": "1.12.1",
    "jsonexport": "3.0.1",
    "lodash": "4.17.20",
    "vue": "2.6.12",
    "vue-i18n": "8.21.0",
    "vue-router": "3.4.3"
  }, 

**First** of all the right-most header entry (TestFirst) is a cv-header-menu and when opening it the text in the menu entries are truncated. (see attached screenshot)
This is my implementation:
<cv-header-nav aria-label="Carbon nav">
          <cv-header-menu :title="user.given_name">
            <cv-header-menu-item @click="openModalProfile">
              {{ menuItems[2].menu[0].label }}
            </cv-header-menu-item>
            <cv-header-menu-item @click="openModalPassword">
              {{ menuItems[2].menu[1].label }}
            </cv-header-menu-item>
            <cv-header-menu-item @click="openModalSubscription">
              {{ $t("header.subscriptions") }}
            </cv-header-menu-item>
            <cv-header-menu-item :to="menuItems[2].menu[2].to">
              {{ $t("header.about") }}
            </cv-header-menu-item>
            <cv-header-menu-item @click="logoutUser">
              {{ menuItems[2].menu[4].label }}
            </cv-header-menu-item>
          </cv-header-menu>
  </cv-header-nav>

**Second** I have to replace the text in the cv-header-menu with an icon. How can I do this?

And **third** when I decrease the size of the window the entries in the menu disappear but my assumption is they should be put in a kind of an overflow menu. (see attached screenshots)

I will try to recreate the issues in a codesandbox example. 

![toolbarTruncated](https://user-images.githubusercontent.com/40664654/94259088-36220880-ff2e-11ea-9879-775267e1e292.png)
![usermenu](https://user-images.githubusercontent.com/40664654/94259091-36ba9f00-ff2e-11ea-85bd-5de151d84b11.png)
![toolbarCorrect](https://user-images.githubusercontent.com/40664654/94259092-36ba9f00-ff2e-11ea-91f8-d88403936808.png)

**Comment by lee-chase** [comment]
OK so you can fix one as per this sample with a bit of CSS https://codesandbox.io/s/carbonvue-cvuishell-15h9e?file=/src/TestComponent.vue

However, the Carbon design system does not normally cater for a dropdown menu on the right side. It instead uses the slide out panels. As per the content switcher used in this example http://vue.carbondesignsystem.com/?path=/story/components-cvuishell--header-base-with-actions-and-right-panels
 
Yes however this is not an automated process as can be seen in this example http://vue.carbondesignsystem.com/?path=/story/components-cvuishell--header-base-with-navigation

An enhancement request could be submitted for issue 3 to automatically add the items from the main menu to the side menu.

**Comment by lee-chase** [comment]
It is not possible to use an icon in the CvHeaderMenu
