### ISSUE TITLE
Standard CvTag should not be tabbable

### ISSUE THREAD

**Issue by KJaspers** [carbon-design-system/carbon-components-vue#1032]
We are using the standard CvTag for displaying purposes only. There is no click handler attached to it.
Why does it have a tabIndex="0". Is this on purpose? For the user it is quite confusing to have a focussed element without being able do something with it.

@carbon/vue version: 2.30.2

**Comment by lee-chase** [comment]
None, this appears to be an overhang from a previous dom structure and can be removed.

**Comment by android-lewis** [comment]
Hi @lee-chase, can :tab-index be removed then?

**Comment by lee-chase** [comment]
> Hi @lee-chase, can :tab-index be removed then?

Yes
