### ISSUE TITLE
 The default kind for cv-button got error

### ISSUE THREAD

**Issue by JasmineFan** [carbon-design-system/carbon-components-vue#1074]
The css seems work. the button color change to default color, but it always show error in the console
[Vue warn]: Invalid prop: custom validator check failed for prop "kind".

**Comment by BryceBarbara** [comment]
Please provide the template code so we know what is being used. Without that, there's no telling what's going on.

**Comment by wandss** [comment]
@JasmineFan not sure if it is the same problem there for you, but this happened with me due a typo.
I was trying to set **kind** with value **"danger-tertiary"** (single dash). According to the documentation the value has double dashes, like so:
**danger--tertiary** 

After setting the right value, the warning has gone. 
Hope this helps.
