### ISSUE TITLE
[CvDataTable] pagination + selected items

### ISSUE THREAD

**Issue by rafaelmaiach** [carbon-design-system/carbon-components-vue#1078]
## Detailed description

Changing pages makes the selected items lose track.

> Describe in detail the issue you're having.

Enables the batch action, as the CvDataTableRow key, I chose the key to be `row[0]` that is my table unique information. I select all the values on the displayed data and change to another page and go back to the previous page. The selected values are not marked as checked anymore. 
PS: this one can be a bug on my implementation. I'll leave some screenshots if it's from my side and someone can help me with the problem.

> Is this a feature request (new component, new icon), a bug, or a general issue?

Bug

> Is this issue related to a specific component?

CvDataTable + CvPagination + CvCheckbox

> What did you expect to happen? What happened instead? What would you like to see changed?

Pagination and Select items working

> What browser are you working in?

Chrome

> What version of the Carbon Design System are you using?

"@carbon/vue": "2.34.1"
"carbon-components": "10.24.0"

## Additional information

![image](https://user-images.githubusercontent.com/13542718/100126286-851be980-2e5c-11eb-9065-7614ab390bac.png)

**Comment by rafaelmaiach** [comment]
A workaround I made on my side:

![image](https://user-images.githubusercontent.com/13542718/100459304-0a450f80-30a4-11eb-84d2-91567bf880c0.png)

Before adding to my code, I tested directly on the carbon component by:

```
1) change the @change on cv-pagination to run a method `onPagination`
2) On the new method onPagination, I emitted the `pagination` event, to keep working as before, but I've also added a new line.
3) This new line is the following code:
this.$nextTick(() => {
   this.updateRowsSelected()
});
```

Btw, I needed to add it on `onSearch` as well to work with searches

![image](https://user-images.githubusercontent.com/13542718/100459389-2779de00-30a4-11eb-8a72-c1195de7d107.png)

**Comment by melnaeem** [comment]
> A workaround I made on my side:
> 
> ![image](https://user-images.githubusercontent.com/13542718/100459304-0a450f80-30a4-11eb-84d2-91567bf880c0.png)
> 
> Before adding to my code, I tested directly on the carbon component by:
> 
> ```
> 1) change the @change on cv-pagination to run a method `onPagination`
> 2) On the new method onPagination, I emitted the `pagination` event, to keep working as before, but I've also added a new line.
> 3) This new line is the following code:
> this.$nextTick(() => {
>    this.updateRowsSelected()
> });
> ```
> 
> Btw, I needed to add it on `onSearch` as well to work with searches
> 
> ![image](https://user-images.githubusercontent.com/13542718/100459389-2779de00-30a4-11eb-8a72-c1195de7d107.png)

This saved my day, thank you
