### ISSUE TITLE
How can i change default max-width of bx--grid ?

### ISSUE THREAD

**Issue by selimdoyranli** [carbon-design-system/carbon-components-vue#1100]
## Summary

Hello, how can i change default max-width value of bx--grid as global? (sass override etc.)

![Screen Shot 2021-01-04 at 11 15 10 PM](https://user-images.githubusercontent.com/22690563/103575745-3a71a080-4ee3-11eb-9b2d-79746fa90060.png)

## Relevant information

i'm using

`"@carbon/vue": "2.27.1",` and nuxt & style-resource-module (scss)

**Comment by lee-chase** [comment]
@selimdoyranli use the fullWidth property and allow the containing element to control the size.

`<cv-grid fullWidth>`
