### ISSUE TITLE
Positioning problem for Accordion component used in a modal (Chrome only)

### ISSUE THREAD

**Issue by KJaspers** [carbon-design-system/carbon-components-vue#1103]
When using the Carbon Vue.js Accordion component in a modal in Chrome there are some problems if several accordion items are expanded and the content is very large.

This is how it looks initially: 
![Screenshot 2021-01-13 at 08 23 30](https://user-images.githubusercontent.com/50624181/104419358-a6ee3e80-5578-11eb-812a-2e44c90e9343.png)

Then I will expand the Development-en and the Production-en accordion item and click a checkbox in the Production-en area. Then the modal looks like this:
![Screenshot 2021-01-13 at 08 25 16](https://user-images.githubusercontent.com/50624181/104419581-f2a0e800-5578-11eb-8bc2-e5ae421e9bcc.png)

This problem was found for Chrome only!

When adding a `position: relative;` style to the modal content, the problem was fixed. I wonder if this should be fixed in the component or in my special case only. Shouldn't the children of `.bx--modal-container` all have the position value `relative`?

**Comment by lee-chase** [comment]
Can you create a codesandbox showing this issue. If it is a styling issue then it needs raising in https://github.com/carbon-design-system/carbon/issues with a reference to this issue.
