### ISSUE TITLE
Property in cv-header-menu component is missing which is used as attribute "title"

### ISSUE THREAD

**Issue by barbarahartel** [carbon-design-system/carbon-components-vue#1106]
The **cv-header-menu** has a property called "title" but it is not used in the generated html element.

The generated element in the DOM tree looks like

      <li class="cv-header-menu bx--header__submenu">... </li>

But it should contain the attribute "title" like 

    <li class="cv-header-menu bx--header__submenu" id="userMenu" _**title="MyName"**_> ... </li>

**Comment by lee-chase** [comment]
You are right 'title' was a poor choice and in general we have tried to avoid re-use of standard dom attributes. 

It is used in
- CvComboBox
- CvDataTable
- CvMultiSelect
- CvHeaderMenu
- CvToastNotification
- CvInlineNotification

A suggested PR could add a new property Carbon uses 'menuLinkName' but re-uses title in other cases.

Perhaps switching use of title and subTitle for a value with some prefix e.g. 'the' or component name based.
```
props: {
  theTitle: String,
  title: String
},
computed: {
  componentTitle() {
    // used by UI
    return title, theTitle;
  },
  attrTitle() {
    // used by UI
    return theTitle ? title : null;
  }
}
```

**Comment by barbarahartel** [comment]
Does it mean that this will be fixed in the next fixpack?
