### ISSUE TITLE
CvPagination component desappear on mobile displays

### ISSUE THREAD

**Issue by christianlmc** [carbon-design-system/carbon-components-vue#1107]
## Detailed description

> Describe in detail the issue you're having.

On https://vue.carbondesignsystem.com/?path=/story/components-cvpagination--default and on my project, when you resize the screen to mobile resolutions the pagination component desappears.

> Is this a feature request (new component, new icon), a bug, or a general issue?

Bug 🐛

> Is this issue related to a specific component?

Yes, CvPagination

> What did you expect to happen? What happened instead? What would you like to see changed?

Expected CvPagination to show on mobile, got an empty bar

This live demo seems to work fine:
https://www.carbondesignsystem.com/components/pagination/usage#live-demo

> What browser are you working in?

Happens in Chrome, Firefox and Samsung Browser

> What version of the Carbon Design System are you using?

"@carbon/vue": "^2.37.0",

## Steps to reproduce the issue

Go to https://vue.carbondesignsystem.com/?path=/story/components-cvpagination--default
Change the width to anything below 892px

## Additional information

- Screenshots
Below 892px width
![image](https://user-images.githubusercontent.com/24314863/105178545-eaabef80-5b06-11eb-8268-aba511d53380.png)

Above 892px width
![image](https://user-images.githubusercontent.com/24314863/105178627-0c0cdb80-5b07-11eb-8b68-0e8c33c2fcde.png)

**Comment by lee-chase** [comment]
It would appear an update to the pagination component styling requires a tweak to the dom to cater for mobile sizes.

**Comment by balhelhas** [comment]
Are there any updates on this bug?
