### ISSUE TITLE
How to set the theme

### ISSUE THREAD

**Issue by paoloproni** [carbon-design-system/carbon-components-vue#1116]
Hi, I would like to set up the $carbon--theme--g90 as fixed theme of my application, but nothing seems to work.
Can you provide me the correct steps ? Thanks
Here is my _carbon.scss:

@import '~@carbon/themes/scss/themes';

$carbon--theme: $carbon--theme--g90;
@include carbon--theme();

@import '~carbon-components/scss/globals/scss/styles';

**Comment by lee-chase** [comment]
https://codesandbox.io/s/carbonvue-starter-274sh?file=/src/styles/_carbon.scss

**Comment by paoloproni** [comment]
It works. 
Thank You Very Much
