### ISSUE TITLE
Translations for cv-date-picker

### ISSUE THREAD

**Issue by paoloproni** [carbon-design-system/carbon-components-vue#1130]
cv-date-picker can open a small window with a calendar, but it seems to me that it is in English only.
I need the Italian version.

I could try to translate it by myselft but it would be nice if there would be an option such as translation="it" or locale maybe.

Without this feature I have to use the version without the calendar

In the documentation I find:
<cv-date-picker
  kind="single"
  :cal-options="calOptions"
  :invalid-message="invalidMessage"
  @change="actionChange"
  :value="value">
  </cv-date-picker>

But it is English only

**Comment by ole1986** [comment]
Seems to be pretty odd but also I could not find any option to individually configure the locale for this component
