### ISSUE TITLE
[CvButton]: Kind validator does not have all possible styles

### ISSUE THREAD

**Issue by KUGDev** [carbon-design-system/carbon-components-vue#1146]
## Detailed description

carbon-components: 10.31.0

src/components/cv-button/button-mixin.js

kind: {
  type: String,
  default: 'primary',
  validator: val => ['', 'primary', 'secondary', 'tertiary', 'ghost', 'danger', 'danger--primary'].includes(val),
}

Danger button variations (danger--ghost and danger--tertiary) are missing in the validator. But the style is ok when I try to use it.

## Additional information

![image](https://user-images.githubusercontent.com/29352750/112651716-b681e180-8e5d-11eb-91eb-66880896e254.png)

![image](https://user-images.githubusercontent.com/29352750/112651407-6acf3800-8e5d-11eb-981e-816928a802bd.png)

**Comment by TimonLukas** [comment]
Good catch @ChoroDev! I put in a PR to fix this.
