### ISSUE TITLE
Date-picker component

### ISSUE THREAD

**Issue by mwasigala** [carbon-design-system/carbon-components-vue#1147]
Date picker misbehaves when its a range

I followed the instruction provided in the vue js code sandbox, 
Unfortunately the end date is not showing and when an icon is clicked to open the calendar an error pops out saying
 Error in v-on handler: "TypeError: a.cal.open is not a function"

but the start date is showing 
![Screenshot 2021-03-26 202322](https://user-images.githubusercontent.com/20720317/112670114-8ba18880-8e71-11eb-8512-bc9b0a00b8e5.png)

**Comment by TimonLukas** [comment]
Hey @mwasigala! Thank you for the report. Unfortunately I can't reproduce this error, in the Storybook everything works. Could you build a minimal reproduction example? Thank you!

**Comment by fbottalico** [comment]
1. Open a new tab with dev tools in Chrome
2. Switch to mobile view
3. Click on the date input or calendar icon in the date input
4. Check console
You should see an error
