### ISSUE TITLE
How to disable cv-header-menu-item?

### ISSUE THREAD

**Issue by klower** [carbon-design-system/carbon-components-vue#1149]
How to disable cv-header-menu-item?

**Comment by TimonLukas** [comment]
Hello @klower! The Carbon Design System doesn't define a `disabled` state for `.bx--header__menu-item`s. But you can still add `disabled` to them like this: `<cv-header-menu-item disabled>...</cv-header-menu-item>`. This will disable the link, but won't disable the element visually - for that you can add custom styles using the selector `.bx--header__menu-item[disabled]` :)

If you'd like to see this feature, please put in a feature request with in the [`carbon-design-system/carbon`](https://github.com/carbon-design-system/carbon) repository. Thank you!
