### ISSUE TITLE
typo in 'cv-data-table-row.vue'

### ISSUE THREAD

**Issue by aniketicloud** [carbon-design-system/carbon-components-vue#1160]
- There is a typo in 'cv-data-table-row.vue' file.
- inside watch -> expanded method -> Ln51,Col43
- currently it is `this.expaned`
- It should be `this.expanded`

`if (this.dataExpanded !== this.expaned) {
        this.dataExpanded = this.expanded;
      }`

**Comment by TimonLukas** [comment]
Thank you for the report @aniketicloud!
