### ISSUE TITLE
Bundle Size stays same independently from Component Usage

### ISSUE THREAD

**Issue by floriankapaun** [carbon-design-system/carbon-components-vue#1192]
I'm not quite sure if this is a Bug, or a problem in my setup, but I noticed that when I include any component of `@carbon/vue`, the whole bundle gets compiled into my build.

There is a section in the README about [Using the Component Library](https://github.com/carbon-design-system/carbon-components-vue/blob/main/packages/core/README.md#using-the-component-library) which says:

> You can register only the components you need if you prefer:
> 
> ```
> Vue.use(CarbonComponentsVue, ['CvButton', 'CvTag']);
> ```

If I do exactly this, I'm finding the full sized carbon-vue.umd.min.js bundled into my vendors.js after a build. The same happens when I manually import one specific component into a .vue file.

There reason I'm not sure if it's a setup problem is because I'm not using the carbon-components with Vue but with Nuxt.

Anyways I'd love to fix this problem and decrease my final bundle size, so looking forward to your feedback. 🙂

**Comment by trickstival** [comment]
If you want tree-shake you could import the components individually and make them global on your own.
Would be nice to have an easier way to do this, and there probably is, but that could be a workaround for now:
```js
import Vue from "vue";
import { CvCheckbox } from "@carbon/vue";

Vue.component(CvCheckbox.name, CvCheckbox);
```

Usage
```vue
<template>
  <div>
    <cv-checkbox />
  </div>
</template>
```

**Comment by floriankapaun** [comment]
I am closing this issue because it is probably long out of date. I think the proposed solution was sufficient.
