### ISSUE TITLE
File Uploader Error Scenario

### ISSUE THREAD

**Issue by SunakshiChagti** [carbon-design-system/carbon-components-vue#1223]
## Detailed description

> When we upload a wrong file, Error message should be displayed. But it is not showing as expected

> Is this a feature request (new component, new icon), a bug, or a general issue?
This is a bug

> Is this issue related to a specific component?
CvFileUploader

> What did you expect to happen? What happened instead? What would you like to see changed?
Error message should be display as design

> What browser are you working in?
Chrome

> What version of the Carbon Design System are you using?
10.23.1

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

## Steps to reproduce the issue

1. Open link : https://vue.carbondesignsystem.com/?path=/story/components-cvfileuploader--default
2. Try uploading wrong file 
3. Error message is not showing

## Additional information

- Screenshots or code
- 
![image](https://user-images.githubusercontent.com/25049278/125927269-cbd48a5e-746e-4209-bda1-34eebe1c7888.png)

- Notes
Expected behavior should be 
![image](https://user-images.githubusercontent.com/25049278/125927544-b60d64cd-af9a-4a4d-8fe1-ddbc26098bbb.png)

**Comment by trickstival** [comment]
I was able to reproduce this issue, but I also noticed [this comment](https://github.com/carbon-design-system/carbon-components-vue/blob/main/packages/core/src/components/cv-file-uploader/cv-file-uploader.vue#L244).

Can I implement the validation of dragged files?
