### ISSUE TITLE
cv-checkbox mixed prop does not show the - 

### ISSUE THREAD

**Issue by joasisk** [carbon-design-system/carbon-components-vue#1230]
## Detailed description

> Describe in detail the issue you're having.
sending the mixed prop as true does not show the dash

> Is this a feature request (new component, new icon), a bug, or a general issue?
bug

> Is this issue related to a specific component?
cv-checkbox

> What did you expect to happen? What happened instead? What would you like to see changed?
the mixed prop to affect the visual

> What browser are you working in?
latest stable chrome on macos

> What version of the Carbon Design System are you using?
latest

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

## Steps to reproduce the issue

1. use cv-checkbox component
2. pass `:mixed="true"`
3. no change

## Additional information

- Screenshots or code
- Notes

**Comment by trickstival** [comment]
Works for me.
Check [this codesandbox](https://codesandbox.io/s/carbon-components-vue-forked-kcwpk?file=/src/TestComponent.vue) out
