### ISSUE TITLE
Automatically calculate tooltip direction

### ISSUE THREAD

**Issue by travis1111** [carbon-design-system/carbon-components-vue#1246]
**Is your feature request related to a problem? Please describe.**
We are displaying a tooltip in a side panel.  The length of the text in front of the tooltip icon various because of translation.  If the translation is very long or very short (which pushes the icon close to the edge of panel), the tooltip is cutoff.

**Describe the solution you'd like**
The position and alignment should be able to automatically calculated. Bootstrap tooltip has a auto position param, does exactly what we want. 

**Describe alternatives you've considered**
None

**Additional context**
![image](https://user-images.githubusercontent.com/35569780/130594352-283dff72-d42d-491d-a502-8b1cb1703938.png)

**Comment by jsumargo** [comment]
I'm having the same problem with the tooltip escaping the top part of its parent.

Saw a recent feature added https://github.com/carbon-design-system/carbon/pull/9556
Would like to see if this can be added here to solve this problem as well.
