### ISSUE TITLE
CvTabs: ARIA attribute 'aria-selected' is not valid for the element <li> with ARIA role 'none'

### ISSUE THREAD

**Issue by barbarahartel** [carbon-design-system/carbon-components-vue#1255]
Access Accessibility Checker found an issue in the CvTabs component.

The text says **ARIA attribute 'aria-selected' is not valid for the element 'li' with ARIA role 'none'** but according to the screenshot the role is "presentation. I don't know why.

I changed the role in the debugger to 'tab' to see whether the issue could be fixed this way and then the issue wasn't reported by the Checker anymore

![image](https://user-images.githubusercontent.com/40664654/134680932-70b4515f-109f-4877-8451-8c3a68fb23bf.png)

**Comment by rodet** [comment]
Hi @barbarahartel . You are right indeed. According to the [MDN documentation](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/presentation_role), `presentation` and `none` are synonym roles. Surprising I agree. Looking at the React code base, it would be safe to have not only the `button` element but also the `li` have the `role=tab`. What do you think @lee-chase ?

**Comment by schuetza** [comment]
Verified, works now . Issue can be closed.
