### ISSUE TITLE
allow icons to be used in the cv-tag

### ISSUE THREAD

**Issue by catdragon** [carbon-design-system/carbon-components-vue#1281]
I have a UI request for the design of a carbon-vue project.  The UX people want a shopping cart icon in the cv-tag so the user knows that the item has not been purchased, but instead is still in the shopping cart.  As far as i can tell this has not been implemented in the code yet.  Attached is a picture of what the designer wants:
![image](https://user-images.githubusercontent.com/7491314/143051028-790825f4-e963-4739-b346-171cf1db8cca.png)
If possible, please let me know when this is implemented. My email is bobby.nichols@ibm.com

**Comment by rodet** [comment]
Hi @catdragon , the Carbon [definition of a tag](https://www.carbondesignsystem.com/components/tag/style) states the following for designers: 
> Tag text should be set in sentence case, and should only have one word. However, if more than one is necessary, then connect the words using a hyphen with no spaces.

It doesn't look like there is an option for placing icons, thus the Vue library doesn't allow it. This would be consistent with the React library as well, which doesn't seem to allow markup in the text.
