### ISSUE TITLE
carbon compatibility with Vue3. 

### ISSUE THREAD

**Issue by OlgaLiber2** [carbon-design-system/carbon-components-vue#1428]
Hello, can carbon be integrated with Vue 3? Some members on my team are having compatibility issues

**Comment by basilv** [comment]
The main branch package.json is using Vue 2 as a dependency. There are tickets tagged with a vue3 label, but unclear how much progress has been made on vue3.

**Comment by OlgaLiber2** [comment]
> The main branch package.json is using Vue 2 as a dependency. There are tickets tagged with a vue3 label, but unclear how much progress has been made on vue3.

I'll close this ticket since we decided we're not going ahead with carbon
