### ISSUE TITLE
CvDatePicker work in progress

### ISSUE THREAD

**Issue by weslleyrsr** [carbon-design-system/carbon-components-vue#1440]
Port CvDatePicker to v3

https://vue.carbondesignsystem.com/?path=/story/components-cvdatepicker--default

**Comment by weslleyrsr** [comment]
**Before merge:**

- [ ] Make sure the component meets all standard accessibility patterns for date pickers
- [ ] Implement all event emitters from the v2 component
- [ ] Handle all parameters from the v2 component
- [ ] Implement all tests from the v2 component
- [ ] Make sure the storybook page replicates all functionality and documentation from the v2 component
- [ ] Make sure it works with v-model

**Comment by davidnixon** [comment]
merged #1453
