### ISSUE TITLE
Updating .gitignore to include storybook build assets and adjust package.json

### ISSUE THREAD

**Issue by grievous0** [carbon-design-system/carbon-components-vue#1441]
This issue addresses the following: 
- The build files from the storybook are flagged to commit upon each local build, and ideally, they should be ignored.
- Some dependencies are not included in package.json, which is error-prone and induces a separate installation.

**Comment by davidnixon** [comment]
https://github.com/carbon-design-system/carbon-components-vue/pull/1443

**Comment by davidnixon** [comment]
merged
