### ISSUE TITLE
Nuxt 3 implementation

### ISSUE THREAD

**Issue by Elaniobro** [carbon-design-system/carbon-components-vue#1456]
## Summary
I am/was a big user of the CDS vue2 library. I have since migrated to Vue/Nuxt 3 and was/am trying to work with the CDS vue3 library. I can't for the life of me figure out how to get the components loaded.

I have tried creating a plugin file as I did with nuxt bridge:

```ts
import CarbonComponentsVue from '@carbon/vue'
import { defineNuxtPlugin } from '~/.nuxt/imports'
import 'carbon-components/css/carbon-components.css'

export default defineNuxtPlugin((nuxtApp) => {
  nuxtApp.vueApp.use(CarbonComponentsVue)
})

```

But I am still unable to get this working. Have any of you folks got this working on your project? I would love to learn how if so.

**Comment by Elaniobro** [comment]
`Cannot find module '@carbon/vue' or its corresponding type declarations`

**Comment by davidnixon** [comment]
Sorry for slow reply. This is probably best discussed in the slack channel [#carbon-vue](https://ibm-marketing-comms.slack.com/archives/CAM5P6NR1)
Do you have a repo link you could share? I have not used Nuxt but I may at least be able to figure out why its not loading.
