### ISSUE TITLE
Which version is used for vue2

### ISSUE THREAD

**Issue by GK-xiao** [carbon-design-system/carbon-components-vue#1458]

**Comment by FuncAccount** [comment]
Hi, I am tring to use Vue2 to develop a website using the carbon design component. Please DM me if you want to connect and discuss issue with it. 
Best,
Le

**Comment by davidnixon** [comment]
This is probably best discussed in the slack channel [#carbon-vue](https://ibm-marketing-comms.slack.com/archives/CAM5P6NR1). Please see comment in #1459
