### ISSUE TITLE
Whether Carbon Vue supports internationalization

### ISSUE THREAD

**Issue by GK-xiao** [carbon-design-system/carbon-components-vue#1459]

**Comment by davidnixon** [comment]
This is probably best discussed in the slack channel [#carbon-vue](https://ibm-marketing-comms.slack.com/archives/CAM5P6NR1)
But I recommend the [i18next](https://www.i18next.com/) with [vue support](https://github.com/i18next/i18next-vue) 

If you are starting a new project, I suggest starting with Vue 3 and the carbon-vue@next components. Not all carbon components are in the next package but it will eventually be complete. For a template app using Vue 3 + Carbon + internationalization see [hello carbon vue 3](https://github.com/IBM/hello-carbon-vue3)
