### ISSUE TITLE
Work in progress cv-inline-loading

### ISSUE THREAD

**Issue by davidnixon** [carbon-design-system/carbon-components-vue#1463]
**Please read** [Vue 3 guidance here](https://github.com/carbon-design-system/carbon-components-vue/tree/vNext#vue-3-guidance)

Port cv-inline-loading to Vue 3

Link to Vue 2 storybook:
https://vue.carbondesignsystem.com/?path=/story/components-cvinlineloading--default

You may want to reference the [Carbon 10 React components](https://v7-react.carbondesignsystem.com/?path=/story/getting-started--welcome)

**Comment by felipebritor** [comment]
Sure. I'll check tomorrow night

**Comment by davidnixon** [comment]
merged
