### ISSUE TITLE
Work in progress CvToggle

### ISSUE THREAD

**Issue by denis2710** [carbon-design-system/carbon-components-vue#1466]
Port CvToggle to Vue 3
https://vue.carbondesignsystem.com/?path=/story/components-cvtoggle--default

**Comment by weslleyrsr** [comment]
Hi @denis2710, my teammate actually create an [issue](https://github.com/carbon-design-system/carbon-components-vue/issues/1460) to work on the toggle component a while ago - the [PR](https://github.com/carbon-design-system/carbon-components-vue/pull/1467) is open already!

FYI @davidnixon
