### ISSUE TITLE
Work in progress CvTooltip (incl. CvInteractiveTooltip, CvDefinitionTooltip)

### ISSUE THREAD

**Issue by OlkaB** [carbon-design-system/carbon-components-vue#1489]
Port CvTooltip, CvInteractiveTooltip, CvDefinitionTooltip to Vue 3

link to Vue 2 storybook:
https://vue.carbondesignsystem.com/?path=/story/components-cvtooltip--default-interactive-tootlip

**Comment by davidnixon** [comment]
merged
