### ISSUE TITLE
The element with role "button" contains descendants with roles which are ignored by browsers

### ISSUE THREAD

**Issue by malupressler** [carbon-design-system/carbon-components-vue#1504]
## Detailed description

> Describe in detail the issue you're having.

The element with role "button" contains descendants with roles "button" which are ignored by browsers
The element with role "button" contains descendants with roles "listbox" which are ignored by browsers
> Is this a feature request (new component, new icon), a bug, or a general issue?

General issue which affects accessibility

> Is this issue related to a specific component?

ComboBox, Dropdown, MultiSelect and basically all the others that have list-box

> What did you expect to happen? What happened instead? What would you like to see changed?

Not appear the accessibility error

> What browser are you working in?

Chrome and Firefox

> What version of the Carbon Design System are you using?

24.5.1 (latest)

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

OSOL

## Steps to reproduce the issue

1. they don't identify so when using the Carbon Multi-Select or any other component that use list-box
2. Pass al the informations that the carbon component would need
3. And the error should pop up in the ibm access accessibility

## Additional information

- Screenshots or code
- Notes
<img width="417" alt="The element with role  button  contains descendants with roles  button  which are ignored by browsers" src="https://github.com/carbon-design-system/carbon-components-vue/assets/80866363/1314bb1e-0f1c-41f9-80a1-ad6add5d96bd">

<img width="389" alt="Screenshot 2023-07-28 at 13 51 22" src="https://github.com/carbon-design-system/carbon-components-vue/assets/80866363/76393297-0c7f-4cdf-84cc-906bcdcd8ada">

**Comment by davidnixon** [comment]
Looking at this in Vue 3
