### ISSUE TITLE
Vue3 File uploader story enhancements

### ISSUE THREAD

**Issue by davidnixon** [carbon-design-system/carbon-components-vue#1519]
## Detailed description
Thanks @felipebritor for the port to Vue 3! A couple of asks to improve the storybook a bit. 

- Button story has misleading text
![image](https://github.com/carbon-design-system/carbon-components-vue/assets/7536103/45b87e72-2b96-4422-8e71-e2bdd75c6980)
This is also in the Vue 2 story. Could you change the default text for this story to "Add file" to match whats is in [React](https://v7-react.carbondesignsystem.com/?path=/story/components-fileuploader--file-uploader) 
- The Vue 2 story has this awkward control to show how the state works.
![image](https://github.com/carbon-design-system/carbon-components-vue/assets/7536103/5f9b0272-b661-44c1-bef3-a176f32fe744)
Could you add something better to show how to use the states. The [React](https://v7-react.carbondesignsystem.com/?path=/story/components-fileuploader--file-uploader) story has "Status for file name (filenameStatus)" control so maybe something like that?
- The vue 2 story sets the default accept to ".jpg,.png" which makes it easier to test the invalid case.
![image](https://github.com/carbon-design-system/carbon-components-vue/assets/7536103/dda4204f-3f91-4bad-a2d3-d33b6159f1f4)

## Additional information

The new port to Vue 3 is really nice!

**Comment by felipebritor** [comment]
Hi, @davidnixon . Sorry for skipping these details! I'll work on it along the week

**Comment by davidnixon** [comment]
I think this one is done.
