### ISSUE TITLE
Restore vue2 storybook website as additional one

### ISSUE THREAD

**Issue by OlkaB** [carbon-design-system/carbon-components-vue#1547]
Hi, it would be more than helpful if Vue2 storybook website would be still available. 
It was fuller (much more examples), with easy code examples to copy, with much clear lists of available props, events etc.

**Comment by dnefi** [comment]
Please check this: https://vue.carbondesignsystem.com/vue2/?path=/story/welcome--default

**Comment by OlkaB** [comment]
@dnefi Perfect, thank you very much
