### ISSUE TITLE
Problems getting started

### ISSUE THREAD

**Issue by dedicated-1** [carbon-design-system/carbon-components-vue#1548]
```
//this works
import { Bee32 } from "@carbon/icons-vue"; 
<Bee32 />
```

**But I can't find the correct tag name (like Bee32) for all the other icons?**
Where can I find them, I've been searching for hours. There are lists of the icons but what do you put in the tag like Bee32. Bee32 is in the example so thats why I know it. Am I retarded?

**Comment by davidnixon** [comment]
lol the vue icons are published from the main carbon site
https://github.com/carbon-design-system/carbon/tree/main/packages/icons-vue

For me I go to the library https://carbondesignsystem.com/guidelines/icons/library/ to find an icon I like and the click the `</>` icon to get the proper name and then I add 32 (or 16 or 20) to it. So in this example I would use:
`import { ModelTuned32 } from "@carbon/icons-vue"; `
![image](https://github.com/carbon-design-system/carbon-components-vue/assets/7536103/2a9ed9fd-1e52-41c0-9591-647447bf9f6d)
