### ISSUE TITLE
Can't find all elements 

### ISSUE THREAD

**Issue by VereschakSun** [carbon-design-system/carbon-components-vue#1551]
Hi!
I started to use your system design,  but I can't fount some components in vue framework.  For example if I opened react components. React maybe has x2 components.

**Comment by davidnixon** [comment]
We do not have Carbon 11 specific components. Its the next big thing that we plan to implement. 

If there is something specific missing let me know and we can probably add it.

**Comment by AndreMorgenstern** [comment]
I can´t find the Popover Component
