### ISSUE TITLE
Improve security practices for `carbon-components-vue`

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon-components-vue#1553]
Hey there, Carbon team member here! 👋 We'd like to ensure the security practices for packages published from the `carbon-design-system` GitHub org are in place and up to date. We'd like to work with you to get the following security practices implemented:

```[tasklist]
- [x] Add a security policy to the repository
- [x] Enable Security advisories
- [x] Enable Private vulnerability reporting
- [x] Enable Dependabot alerts
- [x] Enable Code scanning alerts
- [x] Enable Secret scanning alerts
- [x] Publish your package(s) to npm with [provenance statements](https://docs.npmjs.com/generating-provenance-statements)
```

Most of these can be found under the Security tab for this repository. You may already have most of these implemented and turned on - if so, awesome! 

For establishing a security policy, the existing [security policy for the Carbon monorepo](https://github.com/carbon-design-system/carbon/security/policy) can be used as a template if you'd like. It can be modified to include proper version(s) for your package and any other attributes unique to your project that you may want to highlight.

I'm happy to meet up and chat about this if you'd like, just let me know. Thanks in advance for your help in ensuring security and stability across the Carbon ecosystem! 🙏 💙

**Comment by davidnixon** [comment]
Based on this I ticked some of the boxes above.
![image](https://github.com/carbon-design-system/carbon-components-vue/assets/7536103/e396cb0f-0863-47d5-b043-48d7596ea924)

![image](https://github.com/carbon-design-system/carbon-components-vue/assets/7536103/28b7a945-21ba-4ab9-ba1a-0cbf7e5af9cc)

**Comment by davidnixon** [comment]
I'll try the provenance change with the next publish

**Comment by davidnixon** [comment]
@tay1orjones what setting is this one?
> Enable Security advisories

Also for this one, do I just use the defaults for CodeQL in the settings?
> Enable Code scanning alerts

**Comment by davidnixon** [comment]
@lee-chase FYI

**Comment by davidnixon** [comment]
First try and it worked! Provenance statement is on npm.
<img width="712" alt="image" src="https://github.com/user-attachments/assets/2908b953-0484-470e-8c9d-176d28e6c049">
https://www.npmjs.com/package/@carbon/vue

**Comment by davidnixon** [comment]
@tay1orjones can you advise on the last 2 items for this issue.

what setting is this one?

> Enable Security advisories

Also for this one, do I just use the defaults for CodeQL in the settings?

> Enable Code scanning alerts

**Comment by davidnixon** [comment]
@tay1orjones I think all done now. Will close as resolved.

**Comment by tay1orjones** [comment]
Excellent! Thanks for all your work on this, and sorry for the lack of response. This unfortunately fell off my radar 😓
