### ISSUE TITLE
Cannot install carbon-vue on fresh Vue 3 project

### ISSUE THREAD

**Issue by TNSaturday** [carbon-design-system/carbon-components-vue#1576]
## Detailed description

> Describe in detail the issue you're having.

I'm trying to install @carbon/vue 3 on a new Vue 3 project generated using Vite Vue 3 template.

> Is this a feature request (new component, new icon), a bug, or a general issue?

Bug.

> Is this issue related to a specific component?

No.

> What did you expect to happen? What happened instead? What would you like to see changed?

I expect `npm add` command to run succesfully. Instead got this error message:

```
npm WARN cleanup Failed to remove some directories [
npm WARN cleanup   [
npm WARN cleanup     'C:\\dev\\vue-carbon-emit\\node_modules\\carbon-components',
npm WARN cleanup     [Error: EBUSY: resource busy or locked, rmdir 'C:\dev\vue-carbon-emit\node_modules\carbon-components'] {
npm WARN cleanup       errno: -4082,
npm WARN cleanup       code: 'EBUSY',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: 'C:\\dev\\vue-carbon-emit\\node_modules\\carbon-components'
npm WARN cleanup     }
npm WARN cleanup   ],
npm WARN cleanup   [
npm WARN cleanup     'C:\\dev\\vue-carbon-emit\\node_modules\\@vueuse\\core',
npm WARN cleanup     [Error: EBUSY: resource busy or locked, rmdir 'C:\dev\vue-carbon-emit\node_modules\@vueuse\core\node_modules\vue-demi'] {
npm WARN cleanup       errno: -4082,
npm WARN cleanup       code: 'EBUSY',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: 'C:\\dev\\vue-carbon-emit\\node_modules\\@vueuse\\core\\node_modules\\vue-demi'
npm WARN cleanup     }
npm WARN cleanup   ],
npm WARN cleanup   [
npm WARN cleanup     'C:\\dev\\vue-carbon-emit\\node_modules\\@vueuse\\shared',
npm WARN cleanup     [Error: EBUSY: resource busy or locked, rmdir 'C:\dev\vue-carbon-emit\node_modules\@vueuse\shared\node_modules\vue-demi'] {
npm WARN cleanup       errno: -4082,
npm WARN cleanup       code: 'EBUSY',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: 'C:\\dev\\vue-carbon-emit\\node_modules\\@vueuse\\shared\\node_modules\\vue-demi'
npm WARN cleanup     }
npm WARN cleanup   ]
npm WARN cleanup ]
npm ERR! code 1
npm ERR! path C:\dev\vue-carbon-emit\node_modules\@carbon\vue
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node prepare.js && node .storybook/postinstall.js
npm ERR! node:internal/modules/cjs/loader:1051
npm ERR!   throw err;
npm ERR!   ^
npm ERR!
npm ERR! Error: Cannot find module 'C:\dev\vue-carbon-emit\node_modules\@carbon\vue\prepare.js'
npm ERR!     at Module._resolveFilename (node:internal/modules/cjs/loader:1048:15)
npm ERR!     at Module._load (node:internal/modules/cjs/loader:901:27)
npm ERR!     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
npm ERR!     at node:internal/main/run_main_module:23:47 {
npm ERR!   code: 'MODULE_NOT_FOUND',
npm ERR!   requireStack: []
npm ERR! }
npm ERR!
npm ERR! Node.js v20.6.1
```

> What browser are you working in?

Not browser related.

> What version of the Carbon Design System are you using?

3.0.13

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

Just trying carbon out.

## Steps to reproduce the issue

1. Environment specs: Windows 10, Node.js v20.6.1, NPM v10.4.0
2. Set up new Vue project: `npm create vite@latest app-name -- --template vue`
3. `cd` into directory and run `npm install`
4. Ensure that Vue app itself is running.
5. Run `npm add @carbon/vue`
6. Get an error.

## Additional information
![изображение](https://github.com/carbon-design-system/carbon-components-vue/assets/27682909/c99a2f13-7172-4520-9d72-2805aa14cc04)

**Comment by benceszenassy** [comment]
Hy,

I tried the steps to mimic what you have done, but it worked for me. (Windows 11, Node 20.10.0, NPM 10.2.3)
Based on the error messages (`Error: EBUSY: resource busy or locked`), for me it seems like a windows issue, try installing the package after a windows restart.

**Comment by davidnixon** [comment]
^^ Ditto. osx is good for me:
```
/tmp/app-name$ npm add @carbon/vue

added 26 packages, and audited 55 packages in 46s

10 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```

**Comment by mbwhite** [comment]
@davidnixon I've also seen this issue today; Ubuntu running WSL2   Also on the demo projhect `hello-carbon-vue3`

I'm using Node v20. as well.... not yet debugged into this - contact me via whitemat@uk.ibm.com if I can help

**Comment by morpheux** [comment]
same here osx v20.12.0 arm64

<img width="1012" alt="image" src="https://github.com/carbon-design-system/carbon-components-vue/assets/543362/097680da-6239-41bb-b252-60876dd7d2b3">

**Comment by mbwhite** [comment]
FYI _ I've found that `yarn` does do the installation... worth a try.

**Comment by Ecpii** [comment]
Windows 11 23H2 Node 22.1.0, npm 10.7.0 - same issues here. Specifically targeting 3.0.14 or older versions seems to give the same errors, as well as WSL.

**Comment by mbwhite** [comment]
> Windows 11 23H2 Node 22.1.0, npm 10.7.0 - same issues here. Specifically targeting 3.0.14 or older versions seems to give the same errors, as well as WSL.

I'm using WSL2 as well.  Had to use Yarn to get it to work

**Comment by davidnixon** [comment]
From above output I can see it is trying to run the "**_postinstall**" script in the package which is 
```
node prepare.js && node .storybook/postinstall.js && ibmtelemetry --config=telemetry.yml
```

but why? During the packaging tha script specifically gets renamed to from `postinstall` to **_postinstall** so that it will not run. Why is npm running it like its a lifecycle script?

## this works
1. nvm use 18 - Now using node v18.18.2 (npm v9.8.1)
2. Set up new Vue project: npm create vite@latest app-name -- --template vue
3. cd into directory and run npm install
4. Ensure that Vue app itself is running.
5. Run npm add @carbon/vue

## this fails
1. nvm use 20 - Now using node v20.13.1 (npm v10.5.2)
2. Set up new Vue project: npm create vite@latest app-name -- --template vue
3. cd into directory and run npm install
4. Ensure that Vue app itself is running.
5. Run npm add @carbon/vue


So I think it is some new behaviour with npm 10?


We do have a change in-flight in PR #1593 that changes postinstall to run the ibmtelemetry package but I think that will not fix it for node 20. Try this in node20/npm 10
```sh
npm add @carbon/icon-helpers
```
That package also includes ibmtelemetry and I get this error:
```
npm ERR! code 126
npm ERR! path /private/tmp/app-name-20/node_modules/@carbon/icon-helpers
npm ERR! command failed
npm ERR! command sh -c ibmtelemetry --config=telemetry.yml
npm ERR! sh: /private/tmp/app-name-20/node_modules/.bin/ibmtelemetry: Permission denied
```

So more clues but no solution. :-(

**Comment by liucgbj** [comment]
Verified on Ubuntu 22.04 LTS, Node v20.13.1, npm 10.5.2, no luck and issue still here.

<img width="876" alt="image" src="https://github.com/carbon-design-system/carbon-components-vue/assets/49233035/c35ec3da-8caf-4704-b3e9-4e62f82f2f14">

**Comment by morpheux** [comment]
any news on this? @davidnixon

**Comment by benceszenassy** [comment]
I fiddled with it a little, npm fails but pnpm and yarn works ok in wsl, node 20, npm 10.

I think the difference is when each package manager resolve postinstall scripts.
I cant seem to find a detailed description from how it works, but in the registries they use the original postinstall script, maybe npm read from there and pnpm / yarn read from installed dependencies package.json.

[npm registry](https://registry.npmjs.org/@carbon%2fvue)
```json
...
    "3.0.15": {
      "name": "@carbon/vue",
      "license": "Apache-2.0",
      "version": "3.0.15",
      "description": "A collection of components for the Carbon Design System built using Vue.js",
      "packageManager": "yarn@3.2.0",
      "main": "dist/carbon-vue-3.umd.min.js",
      "types": "src/index.d.ts",
      "web-types": "dist/web-types.json",
      "scripts": {
        "postinstall": "node prepare.js && node .storybook/postinstall.js && ibmtelemetry --config=telemetry.yml",
        "prepack": "pinst --disable",
        "postpack": "pinst --enable",
        "build": "vue-cli-service build --target lib --name carbon-vue-3 ./src/index.js --no-clean",
        "lint": "vue-cli-service lint",
        "build-web-types": "vue-docgen-web-types --outFile dist/web-types.json",
        "add-components-exports": "node addNamedComponentExports.js",
        "ci-check": "yarn add-components-exports && yarn format:diff && yarn test && yarn build && yarn build-web-types",
        "format": "prettier --write '**/*.{scss,css,js,md,vue}' '!**/{build,es,lib,storybook,ts,umd,.coverage}/**'",
        "format:diff": "prettier --list-different '**/*.{scss,css,js,md,vue}' '!**/{dist,storybook-static,.coverage}/**'",
        "format:staged": "prettier --write '**/*.{scss,css,js,md,vue}' '!**/{dist,storybook-static,.coverage}/**'",
        "lint:css": "stylelint '{packages,storybook}/**/*.{vue,scss}'",
        "lint:es": "eslint src/**/*.{js,vue}",
        "lint:style": "vue-cli-service lint:style",
        "serve:storybook": "cd ./storybook && yarn run serve",
        "test": "vue-cli-service test:unit --no-coverage"
      },
...
```

**Comment by KeenanKunzelman** [comment]
I'm also experiencing this on Manjaro currently.

**Comment by davidnixon** [comment]
It's definitely npm 20 + vs yarn or pnpm or npm 18-  and it definitely related to a difference in how the the lifecycle scripts are executed.
The relevant bits are:

json
```
        "postinstall": "node prepare.js && node .storybook/postinstall.js && ibmtelemetry --config=telemetry.yml",
        "prepack": "pinst --disable",
        "postpack": "pinst --enable",
```

in the installed version of package.json it looks like this:
`node_modules/@carbon/vue/package.json`
```json
    "_postinstall": "node prepare.js && node .storybook/postinstall.js && ibmtelemetry --config=telemetry.yml",
    "prepack": "pinst --disable",
    "postpack": "pinst --enable",
```

notice the "_" in front of "_postinstall" this should keep the postinstall script from running but it is running in npm 20+.
My **guess** is that npm 20+ is also running the "postpack" lifecycle task which then enables "postinstall".

**Comment by davidnixon** [comment]
I think the right next step is to move all of the postinstall to a seperate js file and try catch the execution so that errors do not prevent the install.Thoughts?

**Comment by davidnixon** [comment]
@KeenanKunzelman @benceszenassy @morpheux @liucgbj @mbwhite @TNSaturday 

Could I ask you to try again with the tgz attached to PR #1602 
[carbon-vue-3.0.15-4a6cf.tgz](https://github.com/user-attachments/files/15538791/carbon-vue-3.0.15-4a6cf.tgz)

Would be great if you added a comment to the PR or here to say if it worked or not.

**Comment by liucgbj** [comment]
@davidnixon , please see my result below.

**ENV:** Ubuntu 22.04 LTS, Node v20.14.0 npm 10.7.0 mem: 20GB

**Reproduce Steps**

> Step1: run following command `# tar -zxvf carbon-vue-3.0.15-4a6cf.tgz` to extract files from `carbon-vue-3.0.15-4a6cf.tgz`
<img width="520" alt="image" src="https://github.com/carbon-design-system/carbon-components-vue/assets/49233035/3053ef2d-5500-4393-8816-531c8ab34eaa">

> Step2: run following command to install it.
<img width="662" alt="image" src="https://github.com/carbon-design-system/carbon-components-vue/assets/49233035/3ff079c7-7040-4f49-89d5-c813ff08a361">
<img width="1440" alt="image" src="https://github.com/carbon-design-system/carbon-components-vue/assets/49233035/a6740328-2e8b-4df1-9c06-261fd612b367">

**Comment by davidnixon** [comment]
@liucgbj can you try
[carbon-vue-3.0.15-1c45c.tgz](https://github.com/user-attachments/files/15753085/carbon-vue-3.0.15-1c45c.tgz)

Also, for your test case, I think the right command is be `npm install --omit-dev`.
I have not looked at moving the dev install to node 18+.

**Comment by davidnixon** [comment]
@liucgbj I merged a fix for this an its is included in 3.0.16. Please lmk if it works for you. If it does not I will reopen this issue.

**Comment by morpheux** [comment]
@davidnixon using the package you provided it works with 3.0.16 i see this.

![image](https://github.com/carbon-design-system/carbon-components-vue/assets/543362/ce6a954e-e295-4983-932c-ff90aa83ad27)

**Comment by liucgbj** [comment]
@davidnixon , please see below result for `3.0.16`.

**ENV: Ubuntu 22.04 LTS, Node v20.14.0 npm 10.7.0 mem: 20GB**

<img width="530" alt="image" src="https://github.com/carbon-design-system/carbon-components-vue/assets/49233035/b28241ef-c490-4a92-af57-ac1a1a024d4b">
<img width="762" alt="image" src="https://github.com/carbon-design-system/carbon-components-vue/assets/49233035/7ef365ef-e6d6-48e6-b96f-47d05f22ea73">

**Comment by liucgbj** [comment]
@davidnixon , please see below result for `carbon-vue-3.0.15-1c45c.tgz`.

ENV: Ubuntu 22.04 LTS, Node v20.14.0 npm 10.7.0 mem: 20GB

<img width="517" alt="image" src="https://github.com/carbon-design-system/carbon-components-vue/assets/49233035/a05d9d84-85ff-4a92-9e92-1956a1f30137">
<img width="1440" alt="image" src="https://github.com/carbon-design-system/carbon-components-vue/assets/49233035/7b7bd4c8-3bbc-4411-886a-aae989dcec99">

**Comment by guilherme-gm** [comment]
I am still experiencing this issue in 3.0.17.

Here are some things I've observed:
1. The issue seems related to NPM v10 combined with installing from NPM Registry;
2. Installing from zip, from path or from another registry (e.g. Artifactory) doesn't seem to be an issue;
3. NodeJS version doesn't matter (tested in 18 and 20);
4. Using NPM v9 it works fine, but NPM v10 will not.

Here is the error I am seeing:
```
$ npm i @carbon/vue
npm error code 1
npm error path /Users/<redacted>/<redacted>/node_modules/@carbon/vue
npm error command failed
npm error command sh -c node devPreinstall.js && node .storybook/postinstall.js
npm error node:internal/modules/cjs/loader:1143
npm error   throw err;
npm error   ^
npm error
npm error Error: Cannot find module '/Users/<redacted>/<redacted>/node_modules/@carbon/vue/devPreinstall.js'
npm error     at Module._resolveFilename (node:internal/modules/cjs/loader:1140:15)
npm error     at Module._load (node:internal/modules/cjs/loader:981:27)
npm error     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:128:12)
npm error     at node:internal/main/run_main_module:28:49 {
npm error   code: 'MODULE_NOT_FOUND',
npm error   requireStack: []
npm error }
npm error
npm error Node.js v18.20.3
npm error A complete log of this run can be found in: /Users/<redacted>/.npm/_logs/2024-07-08T17_41_31_159Z-debug-0.log
```

what https://github.com/carbon-design-system/carbon-components-vue/issues/1576#issuecomment-2131206962 mentioned seems interesting, we can see that postinstall there is still the dev one.

not the cleanest solution, but I have been wondering whether we could join both postinstalls into a single script and check for the existence of some local file (that is not published)

**Comment by davidnixon** [comment]
latest repro steps:

## this fails
```sh
rm -rf /tmp/npm-20 # if it exists
nvm use 20
npm create vite@latest app-name-20 -- --template vue
cd app-name-20
npm --cache /tmp/npm-20 i
npm --cache /tmp/npm-20 add @carbon/vue
```

## this works
```sh
rm -rf /tmp/npm-20 # if it exists
nvm use 20
npm create vite@latest app-name-20 -- --template vue
cd app-name-20
npm --cache /tmp/npm-20 i
npm pack @carbon/vue
npm --cache /tmp/npm-20 add carbon-vue-3.0.18.tgz
```

So it only fails if installed from registry but not when install from tar ball. Hmmm!

I will use a local registry for future testing

**Comment by davidnixon** [comment]
Will try something like @guilherme-gm suggesting from slack
```javascript
const fs = require('fs');
const { spawnSync } = require('child_process');

if (fs.existsSync('./devPreinstall.js')) {
  require('./devPreinstall.js');
  require('./.storybook/postinstall.js');
} else {
  spawnSync('npx', ['ibmtelemetry', '--config=telemetry.yml']);
}
```

**Comment by davidnixon** [comment]
I think we finally fix this one!
@benceszenassy @guilherme-gm @TNSaturday @liucgbj @morpheux LMK if I need to re-open.
