### ISSUE TITLE
[Vue3] CvCombobox is breaking when using keyboard arrows to navigate the dropdown list

### ISSUE THREAD

**Issue by OlkaB** [carbon-design-system/carbon-components-vue#1604]
## Detailed description

CvCombobox is breaking when using keyboard arrows to navigate the dropdown list

## Steps to reproduce the issue

1. Visit https://vue.carbondesignsystem.com/?path=/story/component-cvcombobox--default
2. Open dropdown
3. Navigate with arrows
4. See the error

## Additional information
![image](https://github.com/carbon-design-system/carbon-components-vue/assets/20342514/cdcc235e-ed89-4c6f-b4b1-12ad6386c227)

**Comment by davidnixon** [comment]
Fixed in #1605
