### ISSUE TITLE
Allow TextInput to include error text and helper text

### ISSUE THREAD

**Issue by StephenHogsten** [carbon-design-system/carbon-components-vue#181]
**Is your feature request related to a problem? Please describe.**
according to the [textinput](https://www.carbondesignsystem.com/components/text-input/code) description, adding a bx--form-requirement element below the element should display a correctly formatted error message.  

**Describe the solution you'd like**
cv-text-input should accept slots for helper text and error text (similar to number-input)

**Describe alternatives you've considered**
This could be done with text properties instead, but slots give more control and this is the strategy already used by numberinput

**Additional context**
Number field looks like it already includes both of these options, so this may already be on the queue for making text-input vue native, I don't know.  I would think cv-text-input is the most common of all the form fields

**Comment by lee-chase** [comment]
Great issue, the core code base is ever evolving so just playing catch up here.

PR on it's way.
