### ISSUE TITLE
Add some more tests

### ISSUE THREAD

**Issue by lee-chase** [carbon-design-system/carbon-components-vue#182]
Currently, only the CvTag component has any tests.

Add more tests (not all at once). Either create a work item or reference this issue.

Tests for
- [x] CvAccordion
- [x] CvBreadcrumb
- [x] CvButton
- [x] CvCheckbox
- [x] CvCodeSnippet
- [ ] CvContentSwitcher
- [ ] CvDataTable
- [ ] CvDatePicker
- [ ] CvDropdown
- [ ] CvFileUploader
- [x] CvNumberInput
- [x] CvInlineLoading
- [x] CvInlineNotification
- [x] CvLink
- [x] CvList
- [x] CvLoading
- [ ] CvModal
- [ ] CvMultiSelect
- [ ] CvOverflowMenu
- [ ] CvPagination
- [ ] CvProgress
- [x] CvRadioButton
- [x] CvSearch
- [ ] CvSelect
- [ ] CvSkeletongText
- [ ] CvSlider
- [ ] CvStructuredList
- [x] CvTabs
- [x] CvTag
- [x] CvTextArea
- [x] CvTextInput
- [ ] CvTile
- [ ] CvTimePicker
- [x] CvToastNotification
- [x] CvToggle
- [x] CvToolbar
- [x] CvTooltip
- [ ] CvUIShell
- [x] CvWrapper

## Note: Tests should include 
 - prop type, default and required checks
 - Snapshots covering each property option
 - Functional tests based on usage

**Comment by ZrianinaMariia** [comment]
@lee-chase I saw `cv-button.test.js` file. Does it mean tests for CvButton are done?

**Comment by ZrianinaMariia** [comment]
Also quite some test for CvButton are failing

**Comment by lee-chase** [comment]
> @lee-chase I saw `cv-button.test.js` file. Does it mean tests for CvButton are done?

Thanks, fixed the button tests.

**Comment by davidnixon** [comment]
I think we can close this now.  Everything in Vue 3 has a test.
