### ISSUE TITLE
Create codepens to illustrate each component

### ISSUE THREAD

**Issue by dcwarwick** [carbon-design-system/carbon-components-vue#203]
**Is your feature request related to a problem? Please describe.**
There are codepens to illustrate the vanilla Carbon components. It would be great to have similar codepends illustrating the Carbon-Vue components.

**Describe the solution you'd like**
A codepen in the Carbon codepen org for each Carbon-Vue component.

**Describe alternatives you've considered**

**Additional context**

**Comment by lee-chase** [comment]
A table sample using props data https://codepen.io/lee-chase/pen/YgVoXR

**Comment by lee-chase** [comment]
Closing this issue. Codepens can be created as and when needed.
