### ISSUE TITLE
Add row select event for Data Table

### ISSUE THREAD

**Issue by ConradSchmidt** [carbon-design-system/carbon-components-vue#222]
**Is your feature request related to a problem? Please describe.**
When using the data table, a row select would be helpful to trigger action based on the selected row

**Describe the solution you'd like**
Event binding on "onRowSelect" with the given row as parameter.

**Describe alternatives you've considered**
Binding the TR-tag manually, but this is a workaround, breaking the vue-DOM concept.

**Additional context**
None

**Comment by lee-chase** [comment]
Added row-select-change event as part of #236, this passes { value, selected } for the row.
