### ISSUE TITLE
Inline styling for dropdown

### ISSUE THREAD

**Issue by ConradSchmidt** [carbon-design-system/carbon-components-vue#223]
**Is your feature request related to a problem? Please describe.**
The normal dropdown styling is quite prominent, and the inline version of dropdown defined by Carbon has a more modest look. Mostly used for filters on top of a data table

**Describe the solution you'd like**
Implementation provided by the Carbon design system:
https://www.carbondesignsystem.com/components/dropdown/code
(Inline Multi-select Dropdown)

**Describe alternatives you've considered**
No real alternatives. Maybe a ghost button, but this is kind of complicated

**Additional context**
None

**Comment by lee-chase** [comment]
See also http://react.carbondesignsystem.com/?selectedKind=DropdownV2&selectedStory=default&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs

**Comment by lee-chase** [comment]
Unlikely to address in v1, this feature is available in V2.
