### ISSUE TITLE
Checkbox story tab is broken

### ISSUE THREAD

**Issue by ConradSchmidt** [carbon-design-system/carbon-components-vue#225]
## Checkbox story tab is broken
When the story tab for the checkbox component is opened, the screen goes blank (except for the "Array v-model" variant).

## Detailed description

> Describe in detail the issue you're having.
Same as above
```
TypeError: Cannot read property 'startLoc' of undefined
    at x (vendors~main.5be00741564a1b1d153e.bundle.js:90)
    at t.createStoryPart (vendors~main.5be00741564a1b1d153e.bundle.js:90)
    at vendors~main.5be00741564a1b1d153e.bundle.js:90
    at Array.forEach (<anonymous>)
    at t.createParts (vendors~main.5be00741564a1b1d153e.bundle.js:90)
    at vendors~main.5be00741564a1b1d153e.bundle.js:90
    at g (vendors~main.5be00741564a1b1d153e.bundle.js:136)
    at Qo (vendors~main.5be00741564a1b1d153e.bundle.js:102)
    at Ci (vendors~main.5be00741564a1b1d153e.bundle.js:102)
    at Ri (vendors~main.5be00741564a1b1d153e.bundle.js:102)
```

> Is this a feature request (new component, new icon), a bug, or a general issue?
Bug

> Is this issue related to a specific component?
Checkbox

> What did you expect to happen? What happened instead? What would you like to see changed?
Story code is shown for all variants

> What browser are you working in?
Chrome

> What version of the Carbon Design System are you using?
9.81.2

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?
None

## Steps to reproduce the issue

1. Open checkbox component in story book
2. Click on the "Story" tab
3. Screen goes blank

## Additional information
I investigated the problem and it is caused by the "Array v-model" story. If the `knobsHelper.getStorySet` function is used, the issue does not occur.
But then the "array" knob-addon is not working
Generally I'm not sure if the "Initial checks" knobs is useful, because it changes nothing. The component can't be reinitialised to use the value of the knob.

**Comment by lee-chase** [comment]
Not sure what's happening maybe try storybook 5 the angular.carbondesignsystem.com has and it looked not too much work.

**Comment by ZrianinaMariia** [comment]
It breaks when 'Array v-model' story is add. Without this story all other stories  works as expected. I will investigate.

**Comment by ZrianinaMariia** [comment]
Sorry @ConradSchmidt, did not noticed your 'additional info' section before, thanks for pointing that out. That's exactly the problem.
