### ISSUE TITLE
DataTable deselect method should have an optional rowIndex parameter

### ISSUE THREAD

**Issue by RyanDubowsky** [carbon-design-system/carbon-components-vue#235]
**Is your feature request related to a problem? Please describe.**
It would be helpful to be able to deselect one or more specific rows from the `DataTable`, rather than all of them (which is the current behavior of `deselect`). 

**Describe the solution you'd like**
To allow for the user to specify one or more `rowIndex` they would like to deselect from the table. 

**Describe alternatives you've considered**
Directly modifying the DOM gets very messy very fast. 

**Additional context**
Separately, the documentation for `DataTable` should be updated to include the `deselect` method, even if no functionality is added.

**Comment by lee-chase** [comment]
Started to do this and decided it was not very Vue. Instead added the ability to use v-model with the table.
```
<cv-data-table
. . .
  v-model="rowSelects"
. . .
</cv-data-table>

<script>
. . .
data() {
  // rowSelects contains values of rows selected.
  return { rowSelects: [] }; 
}

methods: {
  onMyBatchClick() {
    // do stuff
    this.rowSelects = []; // or slice specific row values.
  }
}
</script>
```

Let me know if this works for you.

**Comment by lee-chase** [comment]
Using v1.0.2 https://codepen.io/lee-chase/pen/YgVoXR

**Comment by lee-chase** [comment]
It would appear that the table requires Vue version 2.6.1 as a minimum possible due to https://github.com/vuejs/vue/issues/9330 as nothing else looks like it would impact on this issue 2.6.0 - 2.6.1
