### ISSUE TITLE
Accordion v10 storybook: knobs are not updated when expand/collapse sections

### ISSUE THREAD

**Issue by ZrianinaMariia** [carbon-design-system/carbon-components-vue#309]
## Detailed description

Experimental accordion story (carbon 10): when a user expands / collapses an accordion section directly (not via knobs) knobs values are not updated. I would expect knobs values reflect the current visualised accordion. 

I checked it in Safari and Chrome.

## Steps to reproduce the issue

1. Go to vue.carbondesignsystem.com --> experimental --> accordion
2. Open section 1 of the displayed accordion (not via knobs)
3. Under the knobs tab section 1 is still not open (checkbox is not checked)

## Additional information

I am not sure it is a storybook limitation or a bug.

**Comment by ZrianinaMariia** [comment]
#306

**Comment by lee-chase** [comment]
An interesting idea, however, the knobs are intended as initial input. Where v-model or events are emitted the stories have a separate example interactions.

**Comment by lee-chase** [comment]
Works as expected
