### ISSUE TITLE
Breadcrumb v10: different visual style

### ISSUE THREAD

**Issue by ZrianinaMariia** [carbon-design-system/carbon-components-vue#310]
## Detailed description

The breadcrumb story (experimental carbon 10) looks different from the carbon design website, i.e. font color, hover font color, hover cursor. In addition under 'usage' section in carbon design website there is shown breadcrumbs' space-efficient design, that is not implemented in carbon vue yet.

Vue breadcrumb carbon 10:

<img width="481" alt="image" src="https://user-images.githubusercontent.com/5481483/55399106-80e5de80-554a-11e9-9273-2fe0c82bb704.png">

Carbon design website carbon 10:

![image](https://user-images.githubusercontent.com/5481483/55399140-95c27200-554a-11e9-80e6-b2230cb37cf4.png)

![image](https://user-images.githubusercontent.com/5481483/55399153-9d821680-554a-11e9-9586-6dc98f43ee86.png)

Carbon design website carbon 10, breadcrumbs' space-efficient design:

![image](https://user-images.githubusercontent.com/5481483/55399243-e0dc8500-554a-11e9-85d2-b245970537ca.png)

#306

**Comment by lee-chase** [comment]
The breadcrumb core css does not appear to currently support this implementation.

**Comment by ZrianinaMariia** [comment]
> The breadcrumb core css does not appear to currently support this implementation.

Does it relate to the 'space-efficient design' version?

**Comment by lee-chase** [comment]
> > The breadcrumb core css does not appear to currently support this implementation.
> 
> Does it relate to the 'space-efficient design' version?

Yes, sorry for not being clearer. The story I updated a few days ago but had not merged.

**Comment by ZrianinaMariia** [comment]
> > > The breadcrumb core css does not appear to currently support this implementation.
> > 
> > 
> > Does it relate to the 'space-efficient design' version?
> 
> Yes, sorry for not being clearer. The story I updated a few days ago but had not merged.

Ah, I see. great!

**Comment by lee-chase** [comment]
> > > > The breadcrumb core css does not appear to currently support this implementation.
> > > 
> > > 
> > > Does it relate to the 'space-efficient design' version?
> > 
> > 
> > Yes, sorry for not being clearer. The story I updated a few days ago but had not merged.
> 
> Ah, I see. great!

Is the v10 react version published?

**Comment by ZrianinaMariia** [comment]
> > > > > The breadcrumb core css does not appear to currently support this implementation.
> > > > 
> > > > 
> > > > Does it relate to the 'space-efficient design' version?
> > > 
> > > 
> > > Yes, sorry for not being clearer. The story I updated a few days ago but had not merged.
> > 
> > 
> > Ah, I see. great!
> 
> Is the v10 react version published?

I don't think it is published. But it is possible to run it locally.

**Comment by lee-chase** [comment]
Still an open issue https://github.com/carbon-design-system/carbon/issues/4815
