### ISSUE TITLE
Link font-size is too bold (V10)

### ISSUE THREAD

**Issue by ConradSchmidt** [carbon-design-system/carbon-components-vue#312]
## Detailed description

Font weight of the link is a little bit bolder than in the IBM Design page

![image](https://user-images.githubusercontent.com/3808948/55564086-70bf3200-56f7-11e9-96e3-1dbdd0ea7fbd.png) ![image](https://user-images.githubusercontent.com/3808948/55564135-846a9880-56f7-11e9-986d-9939574900ec.png)
Vue VS Carbon Design
 

> Is this issue related to a specific component?

Link
Also other components (e.g List) - this is more a general issue

> What version of the Carbon Design System are you using?

v2.0.0-alpha.1 (V10) #306

**Comment by lee-chase** [comment]
I think this was due to use of styles from v9 and v10 together. This is now resolved.
