### ISSUE TITLE
Content Switcher v10: differences with the carbon design

### ISSUE THREAD

**Issue by ZrianinaMariia** [carbon-design-system/carbon-components-vue#320]
## Detailed description

In case of content switcher with icons - icons are not vertically aligned. However, I could not find any examples of content switcher with icons on carbon design or carbon react stories  .

<img width="973" alt="Screen Shot 2019-04-05 at 12 56 11 PM" src="https://user-images.githubusercontent.com/5481483/55623073-38c0f900-57a2-11e9-9c73-b4af823f17eb.png">

#306

**Comment by lee-chase** [comment]
This appears to be an issue with the current CSS implementation
https://codepen.io/lee-chase/pen/mgmmEN

See https://github.com/IBM/carbon-components/pull/2290

**Comment by lee-chase** [comment]
Icon appears to be aligned now, closing as resolved.
