### ISSUE TITLE
Data Table V10: differences with the carbon design

### ISSUE THREAD

**Issue by ZrianinaMariia** [carbon-design-system/carbon-components-vue#321]
## Detailed description

1. Checkboxes in the table are not vertically aligned with text.

![image](https://user-images.githubusercontent.com/5481483/55624170-66f40800-57a5-11e9-80b4-4ccc38c0d11f.png)

2. In case of one or more items selected: 'cancel' button should be displayed on the left and number of selected items should be on the right, however I am not sure how strict this rule is.

3. Carbon design does not show any example of how filter and actions icons should look like (however vue storybook has such examples). This point is more like a question than bug.
4. Menu meatballs should be visible only on row hover, not always visible.
5. Columns sorting is missing.

6. Table with pagination: 'Items per page' text is missing ':'.
7. Table with pagination: separator and spacing between 'items per page' and 'a-b of X items' differ from carbon design (separator's colour and height).
8. Table with pagination: dropdown to select page number is missing.
9. Table with pagination: a part that displays how many pages, differ, i.e. should be 'of X pages' instead of '1 of 0'.
10. Table with pagination: left/right nav arrows style differs.
11. Table with pagination: there should be no current page number between nav arrows.

Carbon-vue pagination:
![image](https://user-images.githubusercontent.com/5481483/55624375-ef72a880-57a5-11e9-852b-b66c2d9df384.png)

Carbon design pagination:
![image](https://user-images.githubusercontent.com/5481483/55624392-f994a700-57a5-11e9-8f23-1c0290be5c58.png)

12. 'Slotted HTML' story has problem with sizes. In addition, 'Rule' columns contain links that lead to the 'Default' folder components and it is a bit confusing.

13. Expandable data table story is missing.

#306

**Comment by lee-chase** [comment]
With a small number of fixes the latest 10.1 CSS Vue and React implementations look the same.

This appears to be a core CSS issue.

![image](https://user-images.githubusercontent.com/15086604/55960966-c5b5f780-5c65-11e9-9092-178130a8138e.png)

**Comment by lee-chase** [comment]
A number of these issues are related to the current state of @ZrianinaMariia.

See https://github.com/IBM/carbon-components/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+data+table+

**Comment by lee-chase** [comment]
Expandable functionality should be raised as a separate enhancement request.

**Comment by lee-chase** [comment]
Closing as all resolved
