### ISSUE TITLE
Dropdown v10: differences with the carbon design

### ISSUE THREAD

**Issue by ZrianinaMariia** [carbon-design-system/carbon-components-vue#322]
## Detailed description

1. Inline dropdown in invalid state: not enough spacing between text and icon.

carbon-vue:
![image](https://user-images.githubusercontent.com/5481483/55626711-8a6e8100-57ac-11e9-98db-458b262a3bbb.png)

carbon design:
![image](https://user-images.githubusercontent.com/5481483/55626675-70cd3980-57ac-11e9-8f6d-186b245467b3.png)

2. Inline dropdown: height is bigger than should be.

carbon-vue:
![image](https://user-images.githubusercontent.com/5481483/55626738-9e19e780-57ac-11e9-986d-090e42016d4a.png)

carbon design: 
![image](https://user-images.githubusercontent.com/5481483/55626749-a7a34f80-57ac-11e9-931b-03d634d9fcc5.png)

3. Inline dropdown: when an option was selected, dropdown should be in focused state, i.e. should have blue border.
￼4. Inline dropdown: looks like theme should be inverted, i.e dropdown's background should be the same and title background.

carbon-vue:
![image](https://user-images.githubusercontent.com/5481483/55626806-d0c3e000-57ac-11e9-85ac-44165a9dec0c.png)

carbon design:
![image](https://user-images.githubusercontent.com/5481483/55626812-d7525780-57ac-11e9-92c4-0a0ddaf3d7f9.png)

5. Inline dropdown is missing arrow (when one of the options was selected).
![image](https://user-images.githubusercontent.com/5481483/55626857-f0f39f00-57ac-11e9-9c81-26008bb3e8a9.png)
6. Multiselect dropdown and filterable multiselect are missing.

#306 

￼

**Comment by lee-chase** [comment]
@ZrianinaMariia Multiselect and filterable should be raised as enhancement requests.
