### ISSUE TITLE
Inline loading v10: differences with carbon-react stories

### ISSUE THREAD

**Issue by ZrianinaMariia** [carbon-design-system/carbon-components-vue#324]
1. Carbon react has a 'UX example' story for inline Loading, that shows how after onclick event submit button transforms to 'loading' state and then to 'success' state. Looks quite interesting, however I did not see such an example on carbon design website. So, the first question is should carbon-vue provide such a story as well or not?

2. Carbon react has different naming for a state knob, i.e. 'Loading successful state (success)' instead of 'active'. From my perspective 'active' knob is a bit confusing. So, the question is where 'active' word come from. Is it from carbon design or there is an option to find another wording for such a state?

#306

**Comment by lee-chase** [comment]
Closing, not trying to match the react version property names.
