### ISSUE TITLE
Cypress E2E test fails with Vue + Carbon compoennts

### ISSUE THREAD

**Issue by mshanmu8** [carbon-design-system/carbon-components-vue#339]
I have a Vue app with carbon components that uses cypress for e2e test.

Unfortunately, Cypress fails to run the tests with this error.
`Uncaught SyntaxError: Unexpected token ...`

Upon debugging we find that due to this line in main.ts we get the error.
Vue.use(CarbonComponentsVue);

**Comment by lee-chase** [comment]
OK @mshanmu8, @ZrianinaMariia  first thought would be that this is a babel issue. Not checked recently but the standard Vue CLI project used babel-core@7.0.0-bridge and many projects have moved onto @babel/core. We had a similar issue with Storybook requiring @babel/core and the version of jest used by Vue CLI setup needing babel-core@7.0.0-bridge.

**Comment by mshanmu8** [comment]
I don't use babel but typescript for compilation if it helps.

**Comment by lee-chase** [comment]
> I don't use babel but typescript for compilation if it helps.

I understand, however, the Carbon Vue components are built with JS and depending on how they're imported may need babel.

Google is more likely to provide you with answers at this point. 

Please link to a minimum coded example.

**Comment by mshanmu8** [comment]
With basic vue app, installed @carbon/vue, and imported this into main.ts
```import Vue from "vue";
import App from "./App.vue";
import router from "./router";
import CarbonComponents from '@carbon/vue';

Vue.config.productionTip = false;
Vue.use(CarbonComponents);

new Vue({
  router,
  render: h => h(App)
}).$mount("#app");
```
I was getting this error `@carbon/vue not a module` initially so added `carbon.d.ts` with content `declare module "@carbon/vue";`

**Comment by lee-chase** [comment]
Created a sample project using Vue CLI with the package.json below. Like you, I added a carbon.d.ts file but I was was able to run cypress e2e tests locally. NOTE: This may be as a result of  #403

Please create sample repo if further investigation required.

{
  "name": "typescript-test",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "lint": "vue-cli-service lint",
    "test:e2e": "vue-cli-service test:e2e",
    "test:unit": "vue-cli-service test:unit"
  },
  "dependencies": {
    "@carbon/vue": "^2.2.1",
    "vue": "^2.6.10",
    "vue-class-component": "^7.0.2",
    "vue-property-decorator": "^8.1.0"
  },
  "devDependencies": {
    "@types/jest": "^23.1.4",
    "@vue/cli-plugin-e2e-cypress": "^3.8.0",
    "@vue/cli-plugin-typescript": "^3.8.0",
    "@vue/cli-plugin-unit-jest": "^3.8.0",
    "@vue/cli-service": "^3.8.0",
    "@vue/test-utils": "1.0.0-beta.29",
    "node-sass": "^4.9.0",
    "sass-loader": "^7.1.0",
    "ts-jest": "^23.0.0",
    "typescript": "^3.4.3",
    "vue-template-compiler": "^2.6.10"
  }
}

**Comment by lee-chase** [comment]
closing as no further information provided.
