### ISSUE TITLE
cv-search missing xl style

### ISSUE THREAD

**Issue by dragomirenachiibm** [carbon-design-system/carbon-components-vue#348]
## Detailed description

cv-search missing xl style

## Steps to reproduce the issue

Carbon has xl style for search element, but carbon components vue have just lg and sm
const sizeClass = `bx--search--${this.large ? 'lg' : 'sm'}`;

## Additional information

- Screenshots or code
- Notes

**Comment by lee-chase** [comment]
This was addressed recently in #318 will publish v2.0.0-alpha.3 shortly

**Comment by lee-chase** [comment]
Resolved in v2 beta release

**Comment by dragomirenachiibm** [comment]
Thank you @lee-chase
