### ISSUE TITLE
Adding header or UI Shell component

### ISSUE THREAD

**Issue by skcele** [carbon-design-system/carbon-components-vue#357]
**Is your feature request related to a problem? Please describe.**

I mostly use Carbon Vue for prototyping. Adding the header would help make prototypes more accurate to the final product and make it easier to test its interactions with components like side panels. It would also make for feature parity with other versions of Carbon, although it is experimental right now.

**Describe the solution you'd like**

A header or UI shell component consistent with those of other Carbon versions. I also understand that the UI shell could be a pretty large task, and I think the header alone could be a good starting point if that's possible.

**Describe alternatives you've considered**

I've tried to use the vanilla component and rig it up to work with vue.js with not much success. Also considering making some kind of mock header for visual similarity for the time being.

**Additional context**

https://www.carbondesignsystem.com/experimental/ui-shell/usage

**Comment by timoken** [comment]
Definitely need this. I'm currently starting a new project with carbon-vue and was very disappointed that ui-shell is not included although it's already available for Angular and React. Problem now is that I'll have to use vanilla instead for the time being but I can already see the pain when switch to ui-shell for Vue later when it's available 😞
