### ISSUE TITLE
Structured List (carbon 10): default story

### ISSUE THREAD

**Issue by ZrianinaMariia** [carbon-design-system/carbon-components-vue#364]
Looks like 'Border' knob does not do anything in 'default' story for Structured List (carbon 10).

#306

**Comment by lee-chase** [comment]
Can you determine whether the border option has been removed from Carbon 10 or if it's just not functional?

**Comment by ZrianinaMariia** [comment]
> Can you determine whether the border option has been removed from Carbon 10 or if it's just not functional?

Will do.

**Comment by ZrianinaMariia** [comment]
So, I could not find any knobs similar to 'border' on carbon-react. And I checked carbon design website - could not find any example with different border style. Not sure, what 'border' knob' is supposed to do.

**Comment by lee-chase** [comment]
Adds and removes bx--structured-list--border, which is not implemented in Carbon 10 CSS but that may be an oversight. It still appears in the source shown on the design system website.

Perhaps worth a question on the carbon-components repo.

**Comment by lee-chase** [comment]
See https://github.com/IBM/carbon-components/issues/2340
