### ISSUE TITLE
Tabs (carbon 10): disabled state 

### ISSUE THREAD

**Issue by ZrianinaMariia** [carbon-design-system/carbon-components-vue#366]
It would be great if carbon-vue tabs will have a story that demonstrated disabled state of a tab (similar to what is presented on carbon design website).

#306

**Comment by lee-chase** [comment]
Would you like to submit a PR that adds a knob to enable/disable a tab?

**Comment by ZrianinaMariia** [comment]
> Would you like to submit a PR that adds a knob to enable/disable a tab?
Will try to find some time tomorrow to do that.
