### ISSUE TITLE
Some days in datepicker calendar are missing

### ISSUE THREAD

**Issue by KJaspers** [carbon-design-system/carbon-components-vue#401]
We use the CvDatePicker component with kind="range". 
When opening the calendar, there a some days missing:

![image](https://user-images.githubusercontent.com/50624181/57698489-08e4fb00-7656-11e9-8522-edf1336e3870.png)

You can see this behavior on http://vue.carbondesignsystem.com, too.

I used Firefox 60.6.3esr (64-bit).

**Comment by lee-chase** [comment]
This should now be fixed as of 2.1.0
