### ISSUE TITLE
carbon-components-vue based app does not work in IE11 or Edge (Windows 10)

### ISSUE THREAD

**Issue by KJaspers** [carbon-design-system/carbon-components-vue#402]
We are using several components (CvTile, CvButton, CvSelect, CvDatePicker, CvTabs, CvCheckbox, CvTextInput) in our application. When trying to open it in Internet Explorer 11 or Edge on a Windows 10 machine, we see the following error:

![image](https://user-images.githubusercontent.com/50624181/57699734-b6590e00-7658-11e9-8eb7-1f746c6d7359.png)

At this point the page is blank and the loading stops.

We use webpack to build our app.

I will try to attach sample code in the next days, but I need some time to put it together, because I cannot attach or link our confidential source code. 

We need this fix for our upcoming release at the latest by the end of the month (May 2019).

**Comment by sadmard** [comment]
I created a small sample following the steps on [https://www.carbondesignsystem.com/getting-started/developers/vue#install](https://www.carbondesignsystem.com/getting-started/developers/vue#install).

Note that I had to use "npm run serve" instead of "npm serve". In addition I had to install sass-loader and node-sass.

I added single components cv-link and cv-tile to HelloWorld.vue. 
As long as cv-tile is commented out it works on IE 11 and Edge. Once I uncomment the lines for cv-tile I get errors on both browsers related to the icon @carbon/icons-vue/lib/chevron--down/16.js.

[test-carbon-vue-ie.zip](https://github.com/carbon-design-system/carbon-components-vue/files/3178812/test-carbon-vue-ie.zip)

**Comment by lee-chase** [comment]
After these changes and updating to @carbon/vue v2.1.1

NOTE: Would also recommend Vue ^2.6.2 if using table. No other component so far has been reported as requiring 2.6.2 or later.

### Change package.json to
"browserslist": [
"> 1%",
"last 2 versions",
"ie >= 11"
]

### add a vue.config.js
module.exports = {
transpileDependencies: ["@carbon/vue", "@carbon/icons-vue", "@carbon/icon-helpers"]
};

### IE11
![image](https://user-images.githubusercontent.com/15086604/57788932-df000700-772f-11e9-9a5a-5bc2a559a827.png)

### Edge
![image](https://user-images.githubusercontent.com/15086604/57788565-38b40180-772f-11e9-8243-91c2f7708b46.png)

**Comment by lee-chase** [comment]
@KJaspers please comment and re-open if not resolved.

NOTE: Storybook does not work on IE11 or Edge, please raise as a separate issue if important.

**Comment by sadmard** [comment]
I have added the proposed changes to my sample project 
[test-carbon-vue-ie-v2.zip](https://github.com/carbon-design-system/carbon-components-vue/files/3185858/test-carbon-vue-ie-v2.zip)

I still get errors:

On "npm run serve" compile I see 
![test-carbon-vue-ie-v2-compile](https://user-images.githubusercontent.com/50632387/57834760-4a43ea80-77bd-11e9-9a73-c6aee7a9dc91.png)

In IE Edge debugger I see
![test-carbon-vue-ie-v2-error-edge](https://user-images.githubusercontent.com/50632387/57834784-58920680-77bd-11e9-8d96-eeb1247dc883.png)

**Comment by KJaspers** [comment]
@lee-chase I cannot re-open the issue. I don't have the permissions.

**Comment by lee-chase** [comment]
@sadmard version 2.1.1 does not contain any references to the /lib/ folder in @carbon/icons-vue it instead uses the /es/ folder to get around this issues.

Can you check the version you have in node_modules/@carbon/vue/package.json and make sure it is 2.1.1

**Comment by sadmard** [comment]
@lee-chase I updated the version using "npm update". Seems that did not really cleanup the dependencies.
I did a complete new "npm install" and now it works. 
Thanks a lot.

Now we need to update our product build with correct dependencies and settings to see if we get it working there.

**Comment by lee-chase** [comment]
I tend to use https://www.npmjs.com/package/npm-check-updates

**Comment by eddybrando** [comment]
The official Vue tutorial page (https://vue-step-6--carbon-tutorial-vue.netlify.com/#/) is not working on MS Edge.

The error thrown in the console is `SCRIPT1028: Expected identifier, string or number`.

I have a similar error in my application with the Carbon Components Vue repository.

@lee-chase, could you please consider reopening this issue if you find appropriate?
