### ISSUE TITLE
Pagination count breaks when there are no results to the search or filter

### ISSUE THREAD

**Issue by ShayHall** [carbon-design-system/carbon-components-vue#404]
## Detailed description

> Describe in detail the issue you're having.
When search or filter produces no results, the count of how many items out of total becomes `a negative number - 0 of 0`
> Is this a feature request (new component, new icon), a bug, or a general issue?
This is a bug
> Is this issue related to a specific component?
CvPagination

> What did you expect to happen? What happened instead? What would you like to see changed?
It should say `0-0 of 0` or just `0 of 0`

> What browser are you working in?
Chrome and Firefox
> What version of the Carbon Design System are you using?
1.0.0
> What offering/product do you work on? Any pressing ship or release dates we should be aware of?
IBM Cloud Transformation Advisor

## Steps to reproduce the issue

1. Filter or search list until there are no results

## Additional information

- Screenshots or code
![Screen Shot 2019-05-15 at 11 07 48 AM](https://user-images.githubusercontent.com/13802039/57786569-b6611880-7701-11e9-8208-109bb5667de7.png)
- Notes

**Comment by lee-chase** [comment]
Please update to v1.1.3 where this issue appears to be fixed

v1.0.0
![image](https://user-images.githubusercontent.com/15086604/57843300-e5d95900-77c5-11e9-91c9-1abefd31f799.png)

v1.1.3
![image](https://user-images.githubusercontent.com/15086604/57843329-f7226580-77c5-11e9-8346-1c2903a615f7.png)



https://codepen.io/lee-chase/pen/XQvdjg
