### ISSUE TITLE
Datepicker with kind "range" not fully accessible

### ISSUE THREAD

**Issue by KJaspers** [carbon-design-system/carbon-components-vue#408]
My accessibility checker tool does not accept the datepicker (kind "range") with the following message: "Each form control must have associated label."

This is how the dom tree looks like:
![image](https://user-images.githubusercontent.com/50624181/58179356-542b8900-7ca8-11e9-96eb-5c20b73c9b6d.png)

Seems that the for attribute targets the wrong input (the hidden one)?

**Comment by lee-chase** [comment]
Which version are you using?

The latest version looks like this 
![image](https://user-images.githubusercontent.com/15086604/58241021-0ebc9980-7d44-11e9-9629-4fdc14a1cced.png)

Perhaps if you could use codepen or similar to create an example.

**Comment by KJaspers** [comment]
@lee-chase I use @carbon/vue" version 2.1.1

I assume that the difference to your test is that I'm using cal-options: 
{
  maxDate: new Date(),
  altInput: true,
  altFormat: "my format"
}

**Comment by lee-chase** [comment]
@KJaspers So what are you trying to achieve with this option?

If it's simply to change the date format then this example does this. https://codepen.io/lee-chase/pen/MdQJdP 

As it stands flatpickr is adding an input that has no label. We could try to cope with this in our own code but it would require us to fix the DOM in javascript, however, I believe flatpickr is in error here.

**Comment by lee-chase** [comment]
This no longer appears to be an issue. Assumed resolved by flatpickr updates.
