### ISSUE TITLE
Add correct scss import syntax for projects created with Vue CLI

### ISSUE THREAD

**Issue by timoken** [carbon-design-system/carbon-components-vue#410]
Almost everywhere the docs state the scss includes should be done like this:
`@import '@carbon/themes/scss/index.scss';`

This works fine for React but not for projects created with Vue CLI which will return:
> Can't find stylesheet to import.

So, I tried this which works but it is not very elegant:
`@import '../node_modules/@carbon/themes/scss/themes';`

After tons of Slack messaging back and fourth I found out that this works:
`@import '~@carbon/themes/scss/themes';`

So, all that was needed was the `~` symbol but I couldn't figure out what was wrong. Took me about 2 days until someone finally bumped me on this.

Also, see https://github.com/webpack-contrib/sass-loader#imports

Think this should be pointed out in the docs.

**Comment by lee-chase** [comment]
Thank you for raising this issue @timoken. Theming is not something I've used with carbon components, do you by any chance have a sample project that could be shared.

**Comment by timoken** [comment]
Nevermind Lee, it magically suddenly started to work. Not sure why 🤷‍♂

**Comment by timoken** [comment]
Actually I found the solution here:

https://www.carbondesignsystem.com/tutorial/react-step-1/

![img](https://user-images.githubusercontent.com/38980986/58531239-f2a47680-81e1-11e9-8d81-81805989c01f.jpg)

Think this should be mentioned in the docs somewhere.

Ps: This isn't related to themes. It's just a general issue when importing Carbon dependencies in a new project.
