### ISSUE TITLE
Inconsistent behavior of date range picker

### ISSUE THREAD

**Issue by KJaspers** [carbon-design-system/carbon-components-vue#434]
We found the following very confusing behavior in the date range picker:
1.) Click the startDate and select a range 1.6. to 3.6.
2.) Calendar closes. Click the startDate again and click 4.6.
Expected: new range 1.6. to 4.6.
Actual: 3.6. to 4.6.
3.) Repeat the test by clicking 5.6. Now the new range is 3.6. to 5.6. (as expected!)
4.) Then open startDate again and select 2.6. 
Expected: 2.6. to 5.6.
Actual: 2.6. to 3.6.

This inconsistent behavior is really very confusing for the user!

Can be reproduced with carbon vue story book.

**Comment by lee-chase** [comment]
This appears to be an open issue in the Range plugin provided by flatpickr https://github.com/flatpickr/flatpickr/issues/1575 

Also raised against carbon-components-react here https://github.com/carbon-design-system/carbon/issues/2981

**Comment by KJaspers** [comment]
Any update on this one?

**Comment by lee-chase** [comment]
Sadly no change on FlatPickr range plugin.
