### ISSUE TITLE
problem about input

### ISSUE THREAD

**Issue by YYL1999** [carbon-design-system/carbon-components-vue#454]
l want to use the input (type is password),but i can not hide the button (we can use it to control 
 hide the password or not),can you tell me  how can l use it correctly?? of course ,you can provide api

**Comment by lee-chase** [comment]
Not sure I understand your issue.

Here is an example usage of the text input with type password.  

https://codepen.io/lee-chase/pen/PvVrxG

Are you saying you'd like the password hide/show button to be hidden? If so, when and why do you want this?

**Comment by YYL1999** [comment]
you are right! because  of UI ,l should hide it

**Comment by YYL1999** [comment]
> Not sure I understand your issue.
> 
> Here is an example usage of the text input with type password.
> 
> https://codepen.io/lee-chase/pen/PvVrxG
> 
> Are you saying you'd like the password hide/show button to be hidden? If so, when and why do you want this?

you are right! because of UI ,l should hide it

**Comment by lee-chase** [comment]
You could hide it completely using css

.bx--text-input--password__visibility {
 display: none;
}

**Comment by YYL1999** [comment]
it doesn't work

**Comment by lee-chase** [comment]
You will need to increase the specificity or use !important. See codepen.

**Comment by YYL1999** [comment]
I've tried it. Useless

**Comment by lee-chase** [comment]
Which version are you using?
Can you edit the codepen to show your issue?

**Comment by YYL1999** [comment]
2.3.0  the codepen is different from my computer(style,it's left)

**Comment by lee-chase** [comment]
I'm unable to replicate your issue. Can you fork and edit the codepen to show your problem.

**Comment by YYL1999** [comment]
l want to add api to support it  , because always ui doesn't need that button, maybe  l will pull request

**Comment by YYL1999** [comment]
l have solved it ,Thanks!
