### ISSUE TITLE
Add dropdown component

### ISSUE THREAD

**Issue by lee-chase** [carbon-design-system/carbon-components-vue#47]
**Is your feature request related to a problem? Please describe.**
Add a Vue.js implementation of the carbon dropdown component http://www.carbondesignsystem.com/components/dropdown

**Describe the solution you'd like**
Single file templates, notes and story as per other components.

Ideally, it should not rely on core javascript.

**Describe alternatives you've considered**
Initial version can rely on core carbon javascript.

**Additional context**

**Comment by lee-chase** [comment]
Stephane Rodet  https://github.com/rodet has indicated he is working on this component.

**Comment by rodet** [comment]
@lee-chase you can assign me to that one 👍
