### ISSUE TITLE
cv-radio-group can't be made vertical

### ISSUE THREAD

**Issue by dyc3** [carbon-design-system/carbon-components-vue#481]
**Is your feature request related to a problem? Please describe.**
`cv-radio-group` component can't be made vertical, which is supported by vanilla carbon.

**Describe the solution you'd like**
Be able to specify a `vertical` attribute on a `cv-radio-group`

**Describe alternatives you've considered**

**Additional context**
https://www.carbondesignsystem.com/components/radio-button/code

**Comment by dyc3** [comment]
I'm using `carbon/@vue 2.12.0-rc.1` and this warning appears in my console when using cv-radio-button

```
[Vue warn]: Property or method "labelLeft" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property. 
```

A similar error pops up when using cv-radio-group, but for the `vertical` property instead. #482 works in storybook, but it doesn't seem to be working in my project.

**Comment by lee-chase** [comment]
Just tried this here and it seems to work. Can you post a codepen or snippet?

https://codepen.io/lee-chase/pen/aa1fb099893bb6c91e599878b446b544

**Comment by dyc3** [comment]
My issue appears to have been specifying the package version as `^2.12.0-rc.1` instead of `2.12.0-rc.1`. Strange...
