### ISSUE TITLE
cv-date-picker month arrows are not visible in high contrast mode (Windows)

### ISSUE THREAD

**Issue by KJaspers** [carbon-design-system/carbon-components-vue#485]
This is what you see in high contrast mode (Windows):
![image](https://user-images.githubusercontent.com/50624181/61288286-1722d500-a7c7-11e9-80b4-8266faccf631.png)

**Comment by lee-chase** [comment]
The date picker uses a component called flatpickr which has a number of issues logged against it. The core Carbon components team are currently trying to determine the best course of action.
