### ISSUE TITLE
Add data-vis/gauge component

### ISSUE THREAD

**Issue by lee-chase** [carbon-design-system/carbon-components-vue#49]
**Is your feature request related to a problem? Please describe.**
Add a Vue.js implementation of the carbon guage component http://www.carbondesignsystem.com/data-vis/gauge

**Describe the solution you'd like**
Single file templates, notes and story as per other components.

Ideally, it should not rely on core javascript.

**Describe alternatives you've considered**
Initial version can rely on core carbon javascript.

**Additional context**

**Comment by ZrianinaMariia** [comment]
I started working on implementing this component. It will have the following props: amount, total, suffix and header. As in carbon vanilla implementation (https://www.carbondesignsystem.com/data-visualization/gauge/code), d3 will be a dependency.
