### ISSUE TITLE
Bug when loading cvdropdown

### ISSUE THREAD

**Issue by vykimo** [carbon-design-system/carbon-components-vue#492]
Hi,
when I try to load the library on my Vue code like this :
```
import CarbonComponentsVue from '@carbon/vue/src/index';
Vue.use(CarbonComponentsVue);
```
I get this when it comes to load :
`[1] * ./_cv-dropdown-inner in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./node_modules/@carbon/vue/src/components/cv-dropdown/cv-dropdown.vue?vue&type=script&lang=js&
[1] * ./_cv-dropdown-inner-c10 in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./node_modules/@carbon/vue/src/components/cv-dropdown/cv-dropdown.vue?vue&type=script&lang=js&`

CvDropdown element seems to be broken...

> "@carbon/vue": "^2.12.0"

**Comment by lee-chase** [comment]
Please check that node_modules/@carbon/vue has updated as the internal _cv-dropdown-inner-c10 became the standard cv-dropdown in version 2.2.0 of @carbon/vue.

**Comment by vykimo** [comment]
What do you mean? I can't understand you.
I must use this balise, isn't it ?
`<cv-dropdown>`

**Comment by lee-chase** [comment]
The error above refers to _cv-dropdown-inner-c10 but that does not exist in v2.12.0

Try removing and adding @carbon/vue from node_modules.

If this does not resolve the issue can you post example component usage here, on codepen, github or similar.

**Comment by vykimo** [comment]
Yes it fixed it partially because now I get error in console : 
```
[Vue warn]: Unknown custom element: <cv-dropdown> - did you register the component correctly? For recursive components, make sure to provide the "name" option.
```

**Comment by lee-chase** [comment]
Thank you, just spotted that the component is misnamed. I will update shortly to 2.12.1 and post here when done.

**Comment by vykimo** [comment]
Thank you for the fix ! Have a good day

**Comment by lee-chase** [comment]
@vykimo update published please confirm and close if issue resolved.

**Comment by vykimo** [comment]
Seems its still not ok.. same problem in console with "@carbon/vue@2.12.1"

**Comment by lee-chase** [comment]
Could you post a minimal sample on github or code sandbox?

Will try to debug.

**Comment by vykimo** [comment]
I deleted nodes modules and it works now. thanks!
