### ISSUE TITLE
CvMultiSelect add v-model for user input

### ISSUE THREAD

**Issue by vykimo** [carbon-design-system/carbon-components-vue#494]
Hi,
I know that **CvMultiSelect** is under development, here is my request : 
I have a v-model for the selected content but I'm not able to access and modify user input in filter...
![demo](https://user-images.githubusercontent.com/15012658/61941138-31af3800-af97-11e9-9ea6-114cbd7839d7.jpg)
(See attached img) I want to be able to delete content of user input (when the user is typing ',' char) by accessing to the string variable or by an event.
Give me your feedback !

**Comment by lee-chase** [comment]
I am not minded to add something specifically for this, however, I think you can already achieve the desired behaviour.

See https://codepen.io/lee-chase/pen/ymaRer

**Comment by vykimo** [comment]
Good trick ! Thank you for this.
