### ISSUE TITLE
cv-header-panel doesn't propagate @click event

### ISSUE THREAD

**Issue by vykimo** [carbon-design-system/carbon-components-vue#498]
Hi,
As you can see on the below screen, I try to make a disconnect link in my `cv-header-panel` :
![carbon-bug](https://user-images.githubusercontent.com/15012658/62035878-02940300-b1f1-11e9-879e-fe83850440a6.jpg)
But when I click on it, propagation of @click event is stopped (even with a high z-index of my element) and the panel disappear only (with no call of my logout function).
Is this a bug?

**Comment by lee-chase** [comment]
Can you make a codepen example?

Seems to work here https://codepen.io/lee-chase/pen/e19ba0fce803b33e1357b12d530f6d6d

**Comment by vykimo** [comment]
My bad... with button it's working well.

**Comment by pac0rro** [comment]
For Vue 3 Carbon components this problem still exists. 
If you place CvSelect or select tags, they don't acquire focus when clicked but when using the Tab key. Many input components suffer the same behaviour, which is logical for the top menu bar, but no for a right panel as the Carbon documentation states:

> _Right panel -   **An optional panel that shows additional system level actions or content associated with a system icon in the header**_
