### ISSUE TITLE
Pagination v10: item counter brakes after setting number of items to 0

### ISSUE THREAD

**Issue by git-mischa** [carbon-design-system/carbon-components-vue#499]
## Detailed description

The pagination component can't display the counter, after the number of items being set to 0. The counter is reset to a negative value, determined by the "Items per Page", e.g. "-19-0 of 0 Items" instead of expected "0-0 of 0 Items"
![Screen Shot 2019-07-30 at 11 41 45](https://user-images.githubusercontent.com/20705905/62119052-16a63600-b2bf-11e9-82ff-4a430713faf0.png)

Browser: Chrome v75.0.3770.142

## Steps to reproduce the issue

1. Open http://vue.carbondesignsystem.com/?path=/story/components-cvpagination--default
2. Set Number of Items to 0
3. Changing the value to a higher number still shows broken counter

**Comment by lee-chase** [comment]
You should now find this fixed in 2.12.2

See https://codepen.io/lee-chase/pen/08a5a68ee56116d98090d62651eb192f
