### ISSUE TITLE
Experimental cvComboBox filtering with spaces

### ISSUE THREAD

**Issue by lopesleandrorj** [carbon-design-system/carbon-components-vue#501]
## Detailed description

> Filtering does not work as expected when option name has more than one word.

   When adding labels containing more than one word to the cvComboBox component and allowing the auto-filtering, if you press 'space' at any time when typing an option, the component will auto complete the option for you. The issue is that when we work with more than one word, there is no way to filter the data because as soon as you press space, the component auto-completes with the first option on the list. 
   My suggestion in this case is to let this approach on the  'ENTER' key only. So that it auto completes the option only when users press 'ENTER'
<br>

**Comment by lee-chase** [comment]
Could you raise the second issue as a separate item, perhaps with a codepen to demonstrate as I was unable to repeat.
