### ISSUE TITLE
Add Content Switcher light-theme

### ISSUE THREAD

**Issue by lopesleandrorj** [carbon-design-system/carbon-components-vue#509]
Currently we do not have a light-theme for cv-content-switcher object for the Vue version.

![image](https://user-images.githubusercontent.com/53540938/62935754-50d30580-bd9e-11e9-8e5e-8c74e11a69b0.png)

**Comment by lee-chase** [comment]
@lopesleandrorj is there a light theme for the content switcher in another implementation? If so could you link to it.

If not an issue will need creating in https://github.com/carbon-design-system/carbon.

The content switcher should switch colors when using a carbon theme https://github.com/carbon-design-system/carbon/tree/master/packages/themes

**Comment by lopesleandrorj** [comment]
@lee-chase I could not find any implementation either for angular or react. the image came from the visualization created on sketch (the tool where we create mockups). I tried to apply a different carbon theme but it does not change the layout automatically. Could you please try it just to confirm that it is not a mistake from my side?

Should I create an issue on carbon's gitHub then?

**Comment by lee-chase** [comment]
Hmm. Just tried here and it seems to work as expected with the themes.

Change the theme in styles/_carbon.scss. Is this the desired behaviour or are you looking for?

https://codesandbox.io/s/5zk452o9jp

**Comment by lee-chase** [comment]
This issue will be closed if further information is not provided.
