### ISSUE TITLE
Add data-table components

### ISSUE THREAD

**Issue by lee-chase** [carbon-design-system/carbon-components-vue#51]
**Is your feature request related to a problem? Please describe.**
Add a Vue.js implementation of the carbon data-table components http://www.carbondesignsystem.com/components/data-table

**Describe the solution you'd like**
Single file templates, notes and story as per other components.

Ideally, it should not rely on core javascript.

**Describe alternatives you've considered**
Initial version can rely on core carbon javascript.

**Additional context**

Todo:
- [x] Add filter
- [x] Add selection and associated controls
- [x] Add toolbar
- [x] Add overflow menu to rows
- [x] HTML table cell content
- [x] Update notes file

**Comment by vykimo** [comment]
So is it now released? (version 1.0.0 beta.1)

**Comment by lee-chase** [comment]
The data table is still a work in progress.

It currently does not have all features implemented. I’ve added checkboxes relating to the main items in the issue.

Lee


On 10 Feb 2019, at 19:50, vykimo <notifications@github.com<mailto:notifications@github.com>> wrote:


So is it now released? (version 1.0.0 beta.1)

**Comment by vykimo** [comment]
Do you think It'd be possible to add html content in table data? (like a button or an url in the last case)

**Comment by lee-chase** [comment]
> Do you think It'd be possible to add html content in table data? (like a button or an url in the last case)

Working on it, added a checkbox to this issue.

**Comment by vykimo** [comment]
> 
> 
> > Do you think It'd be possible to add HTML content in table data? (like a button or an URL in the last case)
> 
> Working on it, added a checkbox to this issue.

Yes, I just saw it; it allows batch action, but it doesn't address my problem actually.
I need a single action button at the end of each row (for instance, 'view', 'modify', 'copy link' or whatever)
Btw thank you for your job and you do it well!

**Comment by lee-chase** [comment]
> > > Do you think It'd be possible to add HTML content in table data? (like a button or an URL in the last case)
> > 
> > 
> > Working on it, added a checkbox to this issue.
> 
> Yes, I just saw it; it allows batch action, but it doesn't address my problem actually.
> I need a single action button at the end of each row (for instance, 'view', 'modify', 'copy link' or whatever)
> Btw thank you for your job and you do it well!

Should make next publish http://vue.carbondesignsystem.com/?selectedKind=CvDataTable&selectedStory=slotted%20HTML

**Comment by vykimo** [comment]
Handsome !

**Comment by vykimo** [comment]
Pagination seems not to work ... 
When I add :
`  :pagination="{ numberOfItems: internalData.length }" @pagination="actionOnPagination"`

I get the following error : 
```
[Vue warn]: Error in render: "TypeError: this.data is undefined"
TypeError: "this.data is undefined"
```
