### ISSUE TITLE
Increase width for cv-dropdown when working with small texts

### ISSUE THREAD

**Issue by lopesleandrorj** [carbon-design-system/carbon-components-vue#512]
It is really hard to read cv-dropdown options when working with small texts. Is there a way to create a minimal width for the component, so that users would have a better visualization.

![image](https://user-images.githubusercontent.com/53540938/63079606-28214c00-bf15-11e9-9ce6-ed8dee5692cf.png)

Here is a code pen reproducing the issue.
https://codepen.io/lopesleandrorj/pen/LYPNyeP

- Select the option All

**Comment by lee-chase** [comment]
Seems to be a general Carbon problem so I've raised an issue there.

In the meantime setting a min-width for .bx--dropdown-text would appear to be the only option.

**Comment by lee-chase** [comment]
Does this help you @lopesleandrorj ?

.bx--dropdown__wrapper {
  min-width: 300px;
}
