### ISSUE TITLE
cvComboBox large input text is overlapping icons

### ISSUE THREAD

**Issue by lopesleandrorj** [carbon-design-system/carbon-components-vue#513]
Example:

![image](https://user-images.githubusercontent.com/53540938/63181824-6dce3980-c027-11e9-9919-5d1bd70af694.png)

**Comment by lee-chase** [comment]
This is due to https://github.com/carbon-design-system/carbon/issues/3290

**Comment by lee-chase** [comment]
Temporary fix applied to current canary 2.12.7, will be released with 2.12.7

**Comment by mrsideshowjack** [comment]
The temporary fix is not being applied in our code or in codesandbox, see: https://codesandbox.io/s/carbonvue-combo-box-issue-no-1-dtnqe

**Comment by lee-chase** [comment]
The carbon team appear to have gone with an ellipsis to fix the issue. Works using 10.7.3 CSS.
