### ISSUE TITLE
cv-date-picker has no v-model

### ISSUE THREAD

**Issue by vykimo** [carbon-design-system/carbon-components-vue#514]
Hi,
I don't understand why I cannot add a `v-model` for the component `cv-date-picker`.
How can I set by myself a value ?

**Comment by lee-chase** [comment]
You can set the initial date see https://codepen.io/lee-chase/pen/8f9b9e0cdd3ebf0151c4e22141d9d053

However v-model and updating the date is not currently implemented.

**Comment by vykimo** [comment]
Oh ok. Do you know approximatively when it will be supported ?

**Comment by lee-chase** [comment]
Released in current canary @vykimo
