### ISSUE TITLE
Can CvTooltip  add hover event to show multiple line

### ISSUE THREAD

**Issue by xinlihai** [carbon-design-system/carbon-components-vue#516]
**Is your feature request related to a problem? Please describe.**
right now i can just use interactive tooltip which support click to show some \<p\>tags or \<br\>
but when i want to hover and show these things  i can't find a solution.

**Describe the solution you'd like**
suppert hover event to show multiple line

**Comment by lee-chase** [comment]
The implementation of this tooltip is defined by the Carbon Design System https://www.carbondesignsystem.com/components/tooltip/usage/

Please raise an issue https://github.com/carbon-design-system/carbon for updates to the implementation.

**Comment by xinlihai** [comment]
thank you

**Comment by xinlihai** [comment]
hi, @lee-chase i have open an issue for this, please have a look [#3893](https://github.com/carbon-design-system/carbon/issues/3893)
