### ISSUE TITLE
Using cv-text-input type="password" in cv-modal results in scrollbars

### ISSUE THREAD

**Issue by sadmard** [carbon-design-system/carbon-components-vue#517]
I created a codepen sample https://codepen.io/sadmard/pen/WNepYrv which shows a modal dialog with a normal input field and a modal dialog with a password input field.
The one with the password input field gets scrollbars which seem to be related to the positioning of the password visibility icon.
They disappear if i use display: none for bx--text-input--password__visibility

![Cv-Modal-Password](https://user-images.githubusercontent.com/50632387/63704405-4d725c00-c82b-11e9-88c9-1bf252db7ee7.JPG)

**Comment by lee-chase** [comment]
Which browser are you using?

**Comment by sadmard** [comment]
I can see the problem with the codepen in Firefox 68 and Chrome 76. 

In IE Edge the codepen gets console errors:
![image](https://user-images.githubusercontent.com/50632387/64157983-ff1b1980-ce37-11e9-80ff-cd3f7c25b0f5.png)

**Comment by lee-chase** [comment]
Will raise issue

Please try adding the following in the mean time.

.bx--text-input__field-wrapper .bx--text-input--password__visibility {
    overflow: hidden;
}

**Comment by lee-chase** [comment]
Submitted this issue https://github.com/carbon-design-system/carbon/issues/3952 to core carbon.

In the meantime add overflow: visible to the bx--modal-content as follows

https://codepen.io/lee-chase/pen/xxKjqjb
