### ISSUE TITLE
Property overflow: hidden auto; not applied to .bx--dropdown-list on Firefox

### ISSUE THREAD

**Issue by lopesleandrorj** [carbon-design-system/carbon-components-vue#519]
When working with cv-dropdown, the property "overflow: hidden auto;" from .bx--dropdown-list fails on firefox and safari. It works on Chrome by the way. It impacts the visualization in a way that objects are not visible on the screen, but they are still selectable.

I have this URL where I am applying Carbon layout,
https://sea-carbon.w3ibm.mybluemix.net/search?offeringID=Compose-IBM%20Cloud%20Databases%20for%20Redis&offeringType=BP%20Solution&sellerID=defaut

you can check it out by clicking on the filter icon on the right.

![image](https://user-images.githubusercontent.com/53540938/63719906-61ff2600-c824-11e9-9688-6a0caea379da.png)

Then select "Europe" as Geography.

![image](https://user-images.githubusercontent.com/53540938/63719962-80fdb800-c824-11e9-9125-39eaecd5cf2b.png)

You will see that you will not be able to click on the accordion below the Geography filter. But setting the overflow property to "hidden;" instead of "hidden auto;" solves the issue.

**Comment by lee-chase** [comment]
Unable to see your example, I get a blank page. Are you able to create a quick codepen for this?

It may also be worth raising this here https://github.com/carbon-design-system/carbon as a core carbon css issue.

**Comment by lopesleandrorj** [comment]
@lee-chase it turns out it was an issue from application side. Sorry about that.

**Comment by lee-chase** [comment]
np
