### ISSUE TITLE
Add data-vis/pie chart component

### ISSUE THREAD

**Issue by lee-chase** [carbon-design-system/carbon-components-vue#52]
**Is your feature request related to a problem? Please describe.**
Add a Vue.js implementation of the carbon pie-chart component http://www.carbondesignsystem.com/data-vis/pie-chart

**Describe the solution you'd like**
Single file templates, notes and story as per other components.

Ideally, it should not rely on core javascript.

**Describe alternatives you've considered**
Initial version can rely on core carbon javascript.

**Additional context**

**Comment by ZrianinaMariia** [comment]
I will start working on it. I write it as a comment because I don't have rights to assign myself.
