### ISSUE TITLE
Add data-vis/bar-graph component

### ISSUE THREAD

**Issue by lee-chase** [carbon-design-system/carbon-components-vue#54]
**Is your feature request related to a problem? Please describe.**
Add a Vue.js implementation of the carbon bar-graph component http://www.carbondesignsystem.com/data-vis/bar-graph

**Describe the solution you'd like**
Single file templates, notes and story as per other components.

Ideally, it should not rely on core javascript.

**Describe alternatives you've considered**
Initial version can rely on core carbon javascript.

**Additional context**

Items left to do:

- [x] Make y-axis grid lines optional via an attribute.
- [ ] Enable locales for formatting x and y scale labels.
- [ ] Enable accessibility of generated content
- [ ] Enable client to supply data values to be used on the scales when there is no data.
- [ ] More and better stories. 
- [ ] Full review of API and code.

**Comment by cal-smith** [comment]
Hey! Curious if you would want to contribute this as some kind of wrapper in https://github.com/carbon-design-system/carbon-charts/ ... we've got a core Typescript implementation, and wrappers for Angular and React right now.

**Comment by cal-smith** [comment]
There's not much extra to it (being a superset of JavaScript) ... The angular wrappers are pretty straightforward (ex: [bar-chart](https://github.com/carbon-design-system/carbon-charts/blob/571bee4cde9e071d2fac7415ff11af1100f719fc/packages/angular/src/bar-chart.component.ts), [base-chart](https://github.com/carbon-design-system/carbon-charts/blob/571bee4cde9e071d2fac7415ff11af1100f719fc/packages/angular/src/base-chart.component.ts)).

Starting with relatively simplistic wrappers gets us up and running, and we can totally specialize each package for each framework.

**Comment by moores2** [comment]
Items left to do:

- [ ] Make y-axis grid lines optional via an attribute.
- [ ] Enable accessibility of generated content
- [ ] Enable client to supply data values to be used on the scales when there is no data.
- [ ] More and better stories.

**Comment by lee-chase** [comment]
Charting functionality moved to https://carbon-design-system.github.io/carbon-charts/vue/ make charting requests there.
