### ISSUE TITLE
cv-data-table overflow menu clicking jumps the whole table up

### ISSUE THREAD

**Issue by naftali-ibm** [carbon-design-system/carbon-components-vue#542]
## What package(s) are you using?
2.10.0

- [X] `carbon-components`
- [ ] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.
cv-data-table (which is bigger than the screen and need to scroll down to see lower rows) and when overflow-menu clicked the whole table “jumped” up to the first row.
> Is this issue related to a specific component?

> What did you expect to happen? What happened instead? What would you like to
> see changed?

> What browser are you working in?
all
> What version of the Carbon Design System are you using?

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

## Steps to reproduce the issue

1. Step one
open page with a table larger than the screen
2. Step two
scroll down 
3. Step three
press overflow menu - the table jump to the first line

> Please create a reduced test case in CodeSandbox
>
> - Style and vanilla JS:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/components/examples/codesandbox
> - React:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/react/examples/codesandbox

## Additional information

- Screenshots or code
- Notes

**Comment by lee-chase** [comment]
Unable to reproduce https://codepen.io/lee-chase/pen/yWvgwq

Can you alter this example to fail @naftali-ibm ?

**Comment by naftali-ibm** [comment]
thanks, @lee-chase , indeed when you asked me I realized I've forget to mentioned I'm using the configuration of slotted table (http://vue.carbondesignsystem.com/?path=/story/components-cvdatatable--slotted-html) .
please find my example here: 
https://codepen.io/naftali-ibm/pen/MWgPypB 
you'll see the overflow menu jump for some reason. here in this example its happen only when open the overflow menu at least twice and could just up or down - to the last row I clicked before (seems like it remember the previous section or something like this)

**Comment by lee-chase** [comment]
OK. I see it. 

It occurs when one overflow menu is open but off screen (top or bottom). The clicking on a second overflow menu button causes the first to close and jumps to it with focus.

**Comment by lee-chase** [comment]
Thanks for raising this issue @naftali-ibm the fix is currently available in 2.13.0-canary.4. Please allow a day or so for release of 2.13.0

**Comment by naftali-ibm** [comment]
👍
