### ISSUE TITLE
CvOverflowMenu flooding Shadow DOM

### ISSUE THREAD

**Issue by OldNavi** [carbon-design-system/carbon-components-vue#557]
When using CvOverflowMenu  in a Vue component which are rendered and later removed from page we can notice that Shadow DOM is flooded with <ul> component of CvOverflowMenu and never get cleaned, causing Shadow DOM to grow indefinitely. Seems there is no proper cleanup for CvOverflowMenu.

Steps to reproduce...
1/ Create a simple Vue component  that uses CvOverflowMenu
2/ Render it on page and remove it after sometime.
3/ Repeat step 2 in a loop

Reproduced that in both latest Safari and Firefox.

<img width="1007" alt="image" src="https://user-images.githubusercontent.com/1420875/65437568-b948e400-de2c-11e9-83c3-e964c8522963.png">

**Comment by lee-chase** [comment]
https://codepen.io/lee-chase/pen/gOYQbrZ

**Comment by lee-chase** [comment]
@OldNavi reported this was still happening in some circumstances. Currently, reproducible scenario not clearly defined.

Attempted to using vue-router here
https://codepen.io/lee-chase/pen/NWKmoaJ
