### ISSUE TITLE
cv-number-input missing aria labels on up-icon / down-icon buttons

### ISSUE THREAD

**Issue by pmmatchen** [carbon-design-system/carbon-components-vue#568]
The cv-number-input component is generating buttons without aria labels to indicate their purpose.

![image](https://user-images.githubusercontent.com/3920573/65609243-7185a200-df7d-11e9-996f-ff096bd9931f.png)

`<button type="button" class="bx--number__control-btn up-icon">`
`<button type="button" class="bx--number__control-btn down-icon">`

We are using @carbon/vue 2.12.7 with carbon-components 10.6.1

**Comment by lee-chase** [comment]
Addressed by #573
