### ISSUE TITLE
cv-tabs: tabs are not removed, only appended

### ISSUE THREAD

**Issue by mrsideshowjack** [carbon-design-system/carbon-components-vue#599]
## Detailed description

> Describe in detail the issue you're having.

My team are trying in use `cv-tabs` dynamically, however currently when the srcComponent(s) are updated inside the tabs they are appended to the tabs instead of updating the tabs to remove the ones no longer present.

> Is this a feature request (new component, new icon), a bug, or a general issue?

bug 🐛

> Is this issue related to a specific component?

`cv-tabs`

> What did you expect to happen? What happened instead? What would you like to see changed?

EXPECTED OUTCOME: when updating the tabs input array the tabs should be replaced by the new array, like the behaviour shown in `cv-dropdown`.

ACTUAL OUTCOME: the new array is appended to the existing tabs.

Would like to see the method `cv-tabs` uses to render capable of being updated dynamically

> What browser are you working in?

Chrome

> What version of the Carbon Design System are you using?

Latest

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

None

## Steps to reproduce the issue

https://codesandbox.io/s/carbonvue-tabs-4h0kg

1. create a set of tabs with an empty array over `cv-tab`
2. update that array to input tabs
3. update that array again to see tabs appended

## Additional information

- https://codesandbox.io/s/carbonvue-tabs-4h0kg

**Comment by lee-chase** [comment]
Still an issue https://codesandbox.io/s/carbonvue-tabs-o6488

Set tabset 1, select tab 2, change to tabset 2, make window narrow and note that tab 2 is the current value.
