### ISSUE TITLE
CvSearch inconsistent behavior in toolbar mode

### ISSUE THREAD

**Issue by OldNavi** [carbon-design-system/carbon-components-vue#604]
I've noticed inconsistent behavior of CvSearch component in toobar mode.  
Typing something into search field and click Clear/Close button - leaves search field uncleared and onClearClick()  method isn't called.  However if I navigate to Clear/Close button by changing focus via Tab keypress and clicking Clear/Close button - search field gets cleared (onClearClick()  method is called as noticed in debugger) but CvSearch component doesn't get collapsed as intended in a toolbar mode.

**Comment by lee-chase** [comment]
Can you create a minimal codepen or point to an example that demonstrates this issue?

**Comment by lee-chase** [comment]
Unable to reproduce. Re-open if example created.
