### ISSUE TITLE
CvTabs: Fire selected event upon update to tab items 

### ISSUE THREAD

**Issue by mrsideshowjack** [carbon-design-system/carbon-components-vue#611]
## Detailed description

> Describe in detail the issue you're having.

The event `@tab-selected` fires when the tab items get updated/changed, this makes it difficult to have functioning dynamic tabs as, for example, when you have a menu that will change a tab and also select that new tab at the same time, see example with overflow menu 

> Is this a feature request (new component, new icon), a bug, or a general issue?

Bug? or unsupported use-case

> Is this issue related to a specific component?

`cv-tabs`

> What did you expect to happen? What happened instead? What would you like to see changed?

Expected the event not to fire.
Would like to see `@tab-selected` not to fire when the tab items are updated, or some other method of only getting an event fired when the user clicks one

> What browser are you working in?

Chrome

> What version of the Carbon Design System are you using?

10, @carbon/vue - 2.15.0-canary.5

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

None

## Steps to reproduce the issue

1. watch for tab selected event being fired
2. update the tab items
3. observe `tab-selected` was fired

Or open the code sandbox, open the console and observe when the overflow menu item is clicked

## Additional information

- https://codesandbox.io/s/carbonvue-dynamic-tabs-issue-ivrw3

**Comment by lee-chase** [comment]
Considering this now. It was a mistake I think to use index to switch between tabs internally, this causes problems when the tabs are dynamic. Trying to resolve this without breaking current usage.

**Comment by lee-chase** [comment]
Take a look at the following. In canary.9 I’ve added the ‘no-default-to-first’. In addition CvTabs has been made more resilient to dynamically changing the tabs.

In this version of your code I’ve moved the displayed arrays to computed properties, used onTabClick to set the current tab which is safer (alternatively you could set the selected property of the tab), and also used this.$nextTick in onOverflowChange. The $nextTick is required to allow CvTabs to render before changing the tab.

https://codesandbox.io/s/carbonvue-dynamic-tabs-issue-ww7uw
