### ISSUE TITLE
What's the plan of support Multi-Select Dropdown in Vue ?

### ISSUE THREAD

**Issue by BenHsiung** [carbon-design-system/carbon-components-vue#616]
**Is your feature request related to a problem? Please describe.**
project needed

**Describe the solution you'd like**
support

**Describe alternatives you've considered**
no

**Additional context**
Since it's already support in React and Angular, what's the plan of Vue ? thanks.

**Comment by BenHsiung** [comment]
cool, hope it can be published on time :-)

**Comment by lee-chase** [comment]
Released @BenHsiung https://codepen.io/lee-chase/pen/ce643fc762b75f0dd9da34c15395fd7e
