### ISSUE TITLE
Component cvbutton IE11 - icon as path not displayed

### ISSUE THREAD

**Issue by ksolanogps** [carbon-design-system/carbon-components-vue#642]
### Description

Bug

Component: cvbutton 

Icon as path not displayed on Internet Explorer 11

### Steps to reproduce the issue

1)-Go to open on Internet explorer 11 http://vue.carbondesignsystem.com/?path=/story/components-cvbutton--icon-as-path

### Additional information

The issue seems to be releate to this element "<use xmlns="http://www.w3.org/2000/svg" href="static/media/example-icons.52f0b806.svg#icon--add--solid""  reference />:https://developer.mozilla.org/de/docs/Web/SVG/Element/use

![image](https://user-images.githubusercontent.com/31421400/67607814-04635900-f743-11e9-8a81-66ac9ec41926.png)

**Comment by lee-chase** [comment]
This states that loading from an external URI not supported by IE 11. 

https://developer.mozilla.org/en-US/docs/Web/SVG/Element/use

NOTE: Storybook does not appear to work in IE11 which makes it hard to test.

**Comment by lee-chase** [comment]
Closed as IE 11 does not support the form of SVG Use
