### ISSUE TITLE
disabled for CVMultiSelect while still can select from dropdown

### ISSUE THREAD

**Issue by BenHsiung** [carbon-design-system/carbon-components-vue#653]
When I set disabled for CVMultiSelect, the style looks good, but when click the select box still can select from dropdown and the label also changes, could be a bug ? @lee-chase 
<img width="280" alt="image" src="https://user-images.githubusercontent.com/29943333/67997966-84347a80-fc91-11e9-8b76-ff2ca8fa9105.png">

**Comment by lee-chase** [comment]
Thanks for spotting this, canary to be published shortly.
