### ISSUE TITLE
OverflowMenu toggle not behaving as expected in 2.16.0

### ISSUE THREAD

**Issue by william-glasse** [carbon-design-system/carbon-components-vue#655]
## OverflowMenu in 2.16.0
The overflow menu does not toggle between open and closed as expected.

## Detailed description

> Describe in detail the issue you're having.

The overflow menu does not toggle between open and closed, when repeatedly clicking on the menu vertical ellipsis (the three vertical dots). This seems to be fixed in the 2.15.0-canary.5 version, however, it doesn't have the expected behaviour in 2.16.0.

> Is this a feature request (new component, new icon), a bug, or a general issue?

I have assumed this to be a bug, unless this is indeed the intended behaviour.

> Is this issue related to a specific component?

The OverflowMenu

> What did you expect to happen? What happened instead? What would you like to see changed?

I would have expected that given the menu is open, that when you click on the menu toggle/label (3 vertical dots), the menu closes. Therefore, on repeated clicks, the menu should toggle between open and closed.

> What browser are you working in?

Chrome

> What version of the Carbon Design System are you using?

v2.16.0

## Steps to reproduce the issue

1. Step one - Open sandbox environment at:
 https://codesandbox.io/s/carbonvue-overflowmenuv216-issue-47vxw
 
2. Step two - Observe the incorrect behaviour of the overflow menu.

3. Step three - To observe the intended behaviour, switch the vue version to 2.15.0-canary.5 by updating the package.json.
"@carbon/vue": "2.15.0-canary.5"

**Comment by william-glasse** [comment]
This same unexpected behaviour can be found on the storybook, at http://vue.carbondesignsystem.com/?path=/story/components-cvoverflowmenu--default

**Comment by lee-chase** [comment]
Well spotted, there was a slight change to the DOM in carbon 10.7 which triggered the problem.
