### ISSUE TITLE
Cannot use invalid-message slot for CvTextArea component

### ISSUE THREAD

**Issue by sabinead** [carbon-design-system/carbon-components-vue#671]
I am using CvTextArea to let the user enter multiple email addresses. There may be different failures for several email addresses which I want to show below the text area, f.e.

![image](https://user-images.githubusercontent.com/35919161/68573381-e5193b00-0467-11ea-98ca-8e8178a5031a.png)

I was only able to see the slot if I set the property invalid-message in addition. But then, when clearing the message, the message disappears but the text area box is still highlighted.

I have created a codepen for the 3 scenarios [https://codepen.io/sadmard/pen/xxxJrGy](https://codepen.io/sadmard/pen/xxxJrGy):
- invalid-message property: ok
- invalid-message slot: no error message
- invalid-message slot and property: highlighting is not cleared if error is cleared

Enter error in the text area to see the error, anything else should clear the error.

**Comment by lee-chase** [comment]
Can you create a codepen demonstrating the issue?

This codepen seems to demonstrate what you are trying to achieve.
https://codepen.io/lee-chase/pen/qBBMdOm

**Comment by sabinead** [comment]
@lee-chase 
My codepen demonstrates the issue with Modal2("Show Modal invalid-message slot") and Modal3("Show Modal invalid-message slot and property").  Modal1("Show Modal invalid-message property") works fine, but as I want to show more than one line as error I need to use the slot variant.

To reproduce the issue use the following steps in my codepen:
1. open one of the 3 modal dialogs
2. type in error
    expected: the text area is highlighted and the error message is shown
    Modal1: ok
    Modal2: no error is shown
    ![image](https://user-images.githubusercontent.com/35919161/68751781-77554680-0602-11ea-8cad-a17d3ba0a83f.png)
    Modal3: ok
    ![image](https://user-images.githubusercontent.com/35919161/68751620-30675100-0602-11ea-9204-e91e84b7c7a2.png)

2. type anything else
    expected: the text area is no longer highlighted and the error message is no longer shown
    Modal1: ok
    Modal2: no change as it didn#t show an error
    Modal3: text area is still highlighted
    ![image](https://user-images.githubusercontent.com/35919161/68751416-d36b9b00-0601-11ea-84d2-eade6250b783.png)

**Comment by lee-chase** [comment]
Hmm. It would appear that some time ago I made the mistake of thinking $slots was reactive, it is not. Perhaps if the property 'invalid-message' could be truthy or string, we could decide whether or not to show the invalid-message.

**Comment by lee-chase** [comment]
This pattern exists in a number of places, will need to resolve them all the same way.
