### ISSUE TITLE
How to select one row in a cv-data-table component?

### ISSUE THREAD

**Issue by suchishreejena29** [carbon-design-system/carbon-components-vue#674]
Hi Team,
I am using cv-data-table component in my project and the requirement is to allow the user to select only one row in the data table. The example templates that I can see in the below link supports multi-select. 
http://vue.carbondesignsystem.com/?path=/story/components-cvdatatable--search-labels

Is there a carbon way to select only one row in the cv-data-table-component? If not, Is there an easy way to override the default property of multi-select in these tables?

**Comment by lee-chase** [comment]
Is this for the default behaviour where the selected item is used with the batch actions?

**Comment by suchishreejena29** [comment]
@lee-chase : yes.. cvdatatable with search labels..

**Comment by lee-chase** [comment]
You can do it like this https://codepen.io/lee-chase/pen/yWvgwq

This was achieved by 
- Processing the row select change events manually (not using v-model)
  :rows-selected="rowSelects" @row-select-change="actionRowSelectChange"

    actionRowSelectChange: function(ev) {
      this.rowSelects.shift();
      this.rowSelects.push(ev.value);
    }

- Hiding checkbox in header
th .bx--checkbox-wrapper {
  visibility: hidden;
}

I've aloso used the items-selected scope slot to clear that part of the ui
  <template v-slot:items-selected="{scope}"><span></span></template>

**Comment by lee-chase** [comment]
Closing, no response for 14 days.
