### ISSUE TITLE
cv-data-table-action shows a warning in IE11

### ISSUE THREAD

**Issue by sabinead** [carbon-design-system/carbon-components-vue#676]
## Detailed description

**console:** 

```
[Vue warn]: Error in mounted hook: "TypeError: Unable to get property 'add' of undefined or null reference"
found in
---> <CvDataTableAction> at npm/dbaoc-instance-ui/node_modules/@carbon/vue/src/components/cv-data-table/cv-data-table-action.vue
       <CvDataTable> at npm/dbaoc-instance-ui/node_modules/@carbon/vue/src/components/cv-data-table/cv-data-table.vue
         <UserManagementTable> at npm/dbaoc-instance-ui/src/components/common/DataTable.vue
           <ServiceCredentialsTable> at npm/dbaoc-instance-ui/src/components/access/ServiceCredentialsTable.vue
             <CvTab> at npm/dbaoc-instance-ui/node_modules/@carbon/vue/src/components/cv-tabs/cv-tab.vue
               <CvTabs> at npm/dbaoc-instance-ui/node_modules/@carbon/vue/src/components/cv-tabs/cv-tabs.vue
                 <AccessManagement> at npm/dbaoc-instance-ui/src/components/access/AccessManagement.vue
                   <AccessManagement> at src/components/AccessManagement.vue
                     <Page> at npm/dbaoc-instance-ui/src/co

```

The classList property in the following code is not supported on IE11
```export default {
  name: 'cv-data-table-action',
  mounted() {
    // ensure SVG has
    this.$el.children[0].classList.add('class="bx--toolbar-action__icon');
  },
};
```

**Comment by lee-chase** [comment]
@sabinead are you using the compiled version or source?

**Comment by lee-chase** [comment]
@sabinead are you using the src or compiled versions? If I understand the Vue CLI documentation correctly the compiled version should be using my browserList which is set to ie >= 10.

**Comment by sabinead** [comment]
@lee-chase we are using the src versions of c@carbon/vue 2.18.0 and we are using the following browsersList

"browserslist": [
    "> 1%",
    "last 2 versions",
    "ie >= 11"
  ]

**Comment by lee-chase** [comment]
In the source code for cv-data-table-action does the following solve your problem?

@sabinead  
Does the following solve you problem? 
If so I will update the component

  mounted() {
    // ensure SVG has class
    if (this.$el.children[0].classList) {
      this.$el.children[0].classList.add('bx--toolbar-action__icon');
    } else if (this.$el.children[0].className) {
      // IE 11
      this.$el.children[0].className += ' bx--toolbar-action__icon';
    }
  },

**Comment by lee-chase** [comment]
Alternatively, you could polyfill with https://www.npmjs.com/package/classlist-polyfill

It would appear Babel core does not polyfill SVG on IE 11

**Comment by sabinead** [comment]
Sorry for the late response but with the fix IE11 is still shows a warning:
```

[Vue warn]: Error in mounted hook: "TypeError: Assignment to read-only properties is not allowed in strict mode"

found in

---> <CvDataTableAction> at npm/dbaoc-instance-ui/node_modules/@carbon/vue/src/components/cv-data-table/cv-data-table-action.vue
       <CvDataTable> at npm/dbaoc-instance-ui/node_modules/@carbon/vue/src/components/cv-data-table/cv-data-table.vue
         <DataTable> at npm/dbaoc-instance-ui/src/components/common/DataTable.vue
           <DesktopManagement> at npm/dbaoc-instance-ui/src/components/desktops/DesktopManagement.vue
             <Page> at npm/dbaoc-instance-ui/src/components/Page.vue
               <App> at src/App.vue
                 <Root>
```

Failing statement is 
`this.$el.children[0].className += ' bx--toolbar-action__icon';`
