### ISSUE TITLE
Filterable CvMultiSelect's Tag looks visually incorrect when there are 10 or more items selected

### ISSUE THREAD

**Issue by william-glasse** [carbon-design-system/carbon-components-vue#678]
## Detailed description

> Describe in detail the issue you're having.

On the latest version of carbon-vue, when the CvMultiSelect component is made filterable, when there are more than 10 filters selected, the text of the Filter Tag overlaps with the field text. 

## Steps to reproduce the issue

1. Step one
Visit the storybook at http://vue.carbondesignsystem.com/?path=/story/components-cvmultiselect--default
2. Step two
Make the component filterable by selecting the `filterable` checkbox in the knobs section.
3. Step three
Select more than 10 items from the dropdown to observe unexpected results.

## Additional information

<img width="327" alt="Screenshot 2019-11-13 at 15 19 00" src="https://user-images.githubusercontent.com/56296356/68777660-eeea9c00-0629-11ea-9316-83ae73145a69.png">

**Comment by mrsideshowjack** [comment]
It would also be good if the `label` didn't change to "Filter" when it's `filterable`, but keeps the label prop we input

**Comment by lee-chase** [comment]
This is a core carbon issue and needs raising there.

Will consider suggestions for a temporary fix.
