### ISSUE TITLE
Review: bx--form-item usage

### ISSUE THREAD

**Issue by lee-chase** [carbon-design-system/carbon-components-vue#68]
Is a bx--form-item really needed as part of form components?

carbon-components-react places it around 16

This repo currently 10.

If needed should we use cv-form-item.

**Comment by moores2** [comment]
PR #77 adds bx--form-item to cv-number-input and cv-date-picker, but leaves cv-file-uploader (the only other component with bx--form-item missing) unfixed, because it also needs a label and label description adding to its template. That will be part of a separate PR.

**Comment by lee-chase** [comment]
CvSelect now uses an optional bx--form-item, replicate this behaviour?

**Comment by lee-chase** [comment]
On request other components can mimic the CvSelect behaviour.
