### ISSUE TITLE
CvComboBox: dropdown items not initially visible when combo box has autoFilter=true

### ISSUE THREAD

**Issue by mrsideshowjack** [carbon-design-system/carbon-components-vue#681]
## Detailed description

> Describe in detail the issue you're having.

The dropdown items not initially visible when combo box is has `autoFilter='true'`; to get the items to become visible you need to start typing into the combo box

> Is this a feature request (new component, new icon), a bug, or a general issue?

bug 🐛

> Is this issue related to a specific component?

`CvComboBox`

> What did you expect to happen? What happened instead? What would you like to see changed?

Expected to see dropdown items on click of combo box but did not, needed to enter text 

> What browser are you working in?

chrome

> What version of the Carbon Design System are you using?

2.18.0

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

no

## Steps to reproduce the issue

1. open codesandbox (https://codesandbox.io/s/carbonvue-combo-box-issue-no-2-eij4s)
2. click on the dropdown and see that no items are visible
3. start typing into the combo box and observe items are now visible

## Additional information

![Screen Recording 2019-11-14 at 12 01 54](https://user-images.githubusercontent.com/9937136/68855811-f5831d00-06d6-11ea-9e2e-cc2ce8e40d29.gif)

- Not able to reproduce in Storybook, might help with troubleshooting this

**Comment by lee-chase** [comment]
Reproduction in storybook by adding &knob-auto%20filter=true onto the url
