### ISSUE TITLE
Cannot yarn start

### ISSUE THREAD

**Issue by mrsideshowjack** [carbon-design-system/carbon-components-vue#692]
## Detailed description

> Describe in detail the issue you're having.

Cannot start the storybook in a local server using `yarn start`.

getting a bug where I can’t run `yarn start` , am up to date with upstream master
get one of these for each package

```
ERROR in ./stories/cv-accordion-story.js
Module not found: Error: Can't resolve '@carbon/vue/src/components/cv-accordion/cv-accordion-notes.md' in '/Users/Jack.Mason1@ibm.com/gh/carbon-components-vue/storybook/stories'
 @ ./stories/cv-accordion-story.js 15:24-96
 @ ./stories sync \-story\.js$
 @ ./.storybook/config.js
 @ multi ./node_modules/@storybook/core/dist/server/common/polyfills.js ./node_modules/@storybook/core/dist/server/preview/globals.js ./.storybook/config.js (webpack)-hot-middleware/client.js?reload=true&quiet=true
```

seems like all the `-notes.md` files are not present in `storybook/node_modules/@carbon/vue/src/components/*`

Manually copy and pasting the `-note.md` file to the right node_module directory fill fix the error for that component package

> Is this a feature request (new component, new icon), a bug, or a general issue?

Bug 🐛

> Is this issue related to a specific component?

no

> What did you expect to happen? What happened instead? What would you like to see changed?

> What browser are you working in?

n/a

> What version of the Carbon Design System are you using?

`master` branch

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

no

## ~Steps to reproduce the issue~ Steps taken so far

- `rm -rf node_modules` + `yarn`
- cd /storybook + `rm -rf node_modules` + `yarn`
- `yarn reinstall`
- `rm -rf carbon-components-vue` + git clone + `yarn`
- git clone this repo (not my fork)
- downgrading `@carbon/vue` dependancy in `/storybook`
- upgrading `@carbon/vue` dependancy in `/storybook`

## Additional information

[output.log](https://github.com/carbon-design-system/carbon-components-vue/files/3858845/output.log)

<img width="345" alt="Screenshot 2019-11-18 at 12 34 13" src="https://user-images.githubusercontent.com/9937136/69057510-ef0fe080-0a09-11ea-9694-9ab08d14ccae.png">

**Comment by lee-chase** [comment]
It looks like a change to remove the version from the storybook caused lerna to stop updating the version of @carbon/vue it was targetting. As the version does not match the current canary version it uses a standard npm install. 

Updating the storybook/package.json file to the canary version of @carbon/vue will fix this.

A permanent fix will be added shortly.

**Comment by lee-chase** [comment]
Resolved in the latest release.
