### ISSUE TITLE
Tip text property missing from cv-icon-button

### ISSUE THREAD

**Issue by rac146** [carbon-design-system/carbon-components-vue#703]
Every time I render a cv-icon-button, I get an error that the tipText property is undefined, even if I defined it in my markup (as tip-text). After looking into the code, it seems to be missing from the props object:

https://github.com/carbon-design-system/carbon-components-vue/blob/master/packages/core/src/components/cv-button/cv-icon-button.vue

Am i missing something, or is this a bug?

Using version 2.19.0 and Chrome.

**Comment by lee-chase** [comment]
This is a bug, although the intention is to use label as the assistive text.
