### ISSUE TITLE
NuxtJS icon only displays when imported from folder "lib" 

### ISSUE THREAD

**Issue by moritzgvt** [carbon-design-system/carbon-components-vue#723]
## Detailed description
**Bug:**
Icons imported from "es" folder only displays while editing. 
`import AppSwitcher20 from '@carbon/icons-vue/es/app-switcher/20'` 
As soon as the site is refreshed an error occures: 

![image](https://user-images.githubusercontent.com/39989672/69879989-1ea3d000-12c9-11ea-8e6f-e40f7fda10eb.png)

When the source is changed to the folder "lib" it works. 
`import AppSwitcher20 from '@carbon/icons-vue/lib/app-switcher/20'` 

It would be nice when the icon components would work like the "normal" cv-components.

@carbon/vue 2.19.0
@carbon/icons-vue 10.6.1

Find the related `import` statement in "layouts/default.vue"
https://codesandbox.io/s/nuxt-carbon-sf14f

**Comment by brendanmatkin** [comment]
I've also experienced this using @carbon/vue 2.27.1.

I don't know why BUT I've noticed that occasionally it will work from `es` on a hot reload, but refreshing the page breaks it again. It might be related to something in the nuxt/webpack dev config..

**Comment by gsidsid** [comment]
+1, having the same issue

**Comment by lee-chase** [comment]
This looks to me to be an issue with NUXT not transpiling ES6 modules.

If you amend the build section of your nuxt.config.js file to the following it starts working.

  build: {
    /*
     ** You can extend webpack config here
     */
    transpile: ["@carbon/icons-vue"],
    extend(config, ctx) {}
  }

I'm sure there is a bid of documentation somewhere on the Nuxt site but all I could locate was this plugin mention of es6 modules.

https://nuxtjs.org/guide/plugins#es6-plugins

I couldn't get it to work on your codesandbox but it did locally.

Please close if this helps.

**Comment by lee-chase** [comment]
I suspect this is because node (pre v13) did not support ES6 modules.
