### ISSUE TITLE
CvLink should accept a 'Location' object as the 'to' attribute

### ISSUE THREAD

**Issue by ed2novoa** [carbon-design-system/carbon-components-vue#738]
## Detailed description

When you use the CvLink component and pass to it a `Location` object as the `to` attribute you will get this console error: 
`[Vue warn]: Invalid prop: type check failed for prop "to". Expected String with value "[object Object]", got Object`

![Screen Shot 2019-12-04 at 2 45 12 PM](https://user-images.githubusercontent.com/33237517/70179996-b9732480-16a4-11ea-98b5-cfd9a5d56a29.png)

According to the vue-router  documentation (https://router.vuejs.org/api/#to) the `router-link` can accept a `string` or a `Location` object as the `to` prop, but the CvLink component expects the `to` prop to always be a string.  That's on `src/mixins/link-mixin.js` line 4:
```
export default {
  props: {
    disabled: Boolean,
    to: String,
    href: String,
  },
...
```
This is not affecting the functionality of the `router-link` but the console is constantly warning about something that is not a real issue. 

To fix this we just need to set the `to` prop in the `CvLink` component to also expect an `Object` as the prop type.

## Steps to reproduce the issue

1. Make use of the `CvLink` component and pass to it a `Location` object as the `to` parameter.
2. Open the browser dev tools and look at the console.

## Additional information

`Location` interface https://github.com/vuejs/vue-router/blob/dev/types/router.d.ts#L125

**Comment by lee-chase** [comment]
Happy to make the changes. Would you be able to create a sample codepen or sandbox to show demonstrate use of a Location?

**Comment by lee-chase** [comment]
Actually think I can use this to check https://codesandbox.io/s/qx3orn736q

**Comment by ed2novoa** [comment]
Thanks a lot Lee!
