### ISSUE TITLE
[CvDropdown] - Component style/design is not displaying properly

### ISSUE THREAD

**Issue by caiobozato** [carbon-design-system/carbon-components-vue#739]
## Detailed description

> I'm trying to use the Dropdown component but it's not displaying properly. The option shown has a bullet point. Also, the input controller doesn't have the arrow.

> General issue

>Related to [CvDropdown]

> I'm using Chrome

> I'm using the 2.19.0 version

> I work for Systems Special Projects as an application developer

## Steps to reproduce the issue

1. Add <cv-dropdown> component to your project
2. See the preview

## Additional information

![image](https://user-images.githubusercontent.com/26546511/70256099-a3c63380-1766-11ea-82d5-648966c68a39.png)

**Comment by lee-chase** [comment]
Hi, could you confirm the version of carbon-components installed in your node_modules folder?

**Comment by caiobozato** [comment]
I entered the package.json under node_modules/carbon-components and got this:
![image](https://user-images.githubusercontent.com/26546511/70321375-ef7bea00-1805-11ea-8018-fbb0306134a0.png)

**Comment by lee-chase** [comment]
Version 2 of @carbon/vue does not work with v9 of carbon-components. If you remove carbon-components from your package.json it should be installed as a dependency of Vue. This should give you version 10.7.3 currently.

**Comment by caiobozato** [comment]
I got this screenshot from the package.json under `@carbon/vue`. Is that a way to update this?

**Comment by lee-chase** [comment]
Not sure how you have such an old version being included. @carbon/vue started with 9.39.0 and changed to 10.0.0 with v2 of @carbon/vue.

See if you can track down another package.json asking for this version. @carbon/vue v2 requires carbon-components 10

**Comment by lee-chase** [comment]
Can you post a link to your repo? If IBM internal send it to me over email/slack.

**Comment by lee-chase** [comment]
Assumed resolved, not a code issue.
