### ISSUE TITLE
Typo in variable name, can't change end date in range picker

### ISSUE THREAD

**Issue by vladolalik** [carbon-design-system/carbon-components-vue#759]
Probably typo in this line is causing issues with date picker components. 
https://github.com/carbon-design-system/carbon-components-vue/blob/master/packages/core/src/components/cv-date-picker/cv-date-picker.vue#L247

**Comment by vladolalik** [comment]
```
          secondDate = dateToString(this.vdataValuealue.endDate);
```

**Comment by lee-chase** [comment]
Fixed in current canary.
