### ISSUE TITLE
cv data table expandable row doesn't work in IE11

### ISSUE THREAD

**Issue by yobvicky** [carbon-design-system/carbon-components-vue#764]
## Detailed description

> Describe in detail the issue you're having.
In cv-data-table-row.vue component, td colspan=9999 property in the expandable row is not recognized in IE11. It limits itself to one column only.

> Is this a feature request (new component, new icon), a bug, or a general issue?
Bug
> Is this issue related to a specific component?
cv-data-table -> cv-data-table-row
> What did you expect to happen? What happened instead? What would you like to see changed?
Expected result - The expanded row should stretch to 100% width of the table.
Actual result - The expanded row shrinks to only one column in IE11
> What browser are you working in?
IE11
> What version of the Carbon Design System are you using?
2.17.1
> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

## Steps to reproduce the issue

1. Install carbon vue and carbon data table.
2. Click on chevron arrow to show expandable row

- Screenshots or code
- Notes

**Comment by lee-chase** [comment]
I may have over-egged the colspan for which values over 1000 are considered invalid.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/td

Can you confirm whether or not a value of '999' works? I will publish a canary with a reduced value later.

**Comment by yobvicky** [comment]
It works. Wish you guys responded sooner. Had to do a whole lot of tweaking to rewrite the expandable row locally. Anyway appreciate the fix. Thanks  :)

**Comment by lee-chase** [comment]
Sorry for the time taken to get back in the first place, sadly took longer than usual over Christmas.
