### ISSUE TITLE
CvDatePicker ignores initial value

### ISSUE THREAD

**Issue by miha-plesko** [carbon-design-system/carbon-components-vue#773]
## Detailed description

> Describe in detail the issue you're having.

Trying to use CvDatePicker to pick date. Want to have a date picked and displayed by default, but it doesn't work.

> Is this a feature request (new component, new icon), a bug, or a general issue?

Bug. This should work, is even used in official Storybook (http://vue.carbondesignsystem.com/?path=/story/components-cvdatepicker--single). Notice how `:value` is set, but the datepicker doesn't show it.

> Is this issue related to a specific component?

Yes, CvDatePicker.

> What did you expect to happen? What happened instead? What would you like to see changed?

When I use `v-model` or `:value` property I expect the datepicker to display the initial value that I set. But no initial date is picked.

> What browser are you working in?

Chrome

> What version of the Carbon Design System are you using?

carbon-components@10.9.0 
@carbon/vue@2.20.0 

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

Personal project

## Steps to reproduce the issue

1. Step one: Go to http://vue.carbondesignsystem.com/?path=/story/components-cvdatepicker--single
2. Step two: Notice how `:value` is set, but not displayed on the picker

## Additional information

- Screenshots

<img width="1037" alt="Capture" src="https://user-images.githubusercontent.com/8102426/72216015-82055c80-351b-11ea-943e-57f917532fd9.PNG">

**Comment by miha-plesko** [comment]
The isse seems to be this line here: https://github.com/carbon-design-system/carbon-components-vue/blob/master/packages/core/src/components/cv-date-picker/cv-date-picker.vue#L202, if I replace the commend with 
```
this.$refs.date.value = this.value;
```
it works

**Comment by lee-chase** [comment]
Fixed in latest canary

**Comment by paoloproni** [comment]
It has happened to me as well, in a custom module. The v-model was working sometimes as well. I have replaced the cv-date-picker with cv-text-input and it worked.
My version of carbon/vue is 2.37.1
