### ISSUE TITLE
Problem with decimal in number input

### ISSUE THREAD

**Issue by joasisk** [carbon-design-system/carbon-components-vue#774]
when decimals are enabled - and i input the decimal point the zeroes are automatically filled in
```
<cv-number-input
    v-model="rate4"
    label="Q4"
    :min="0"
    :step="0.001"
/>
```
the problem is there also when trying to erase the decimals with backspace... after a moment the zeroes fill back in
stepping with arrows works as it should just manual input has this issue

**Comment by lee-chase** [comment]
Should be fixed in latest canary, please re-open if not functional.
