### ISSUE TITLE
'X' button must have discernible text in Modal and Notification components

### ISSUE THREAD

**Issue by blackcocopug** [carbon-design-system/carbon-components-vue#812]
When you use the CvModal and CvNotification components, is showing an issue on the close button in the top right corner of the modals and notifications. 

![Captura de Pantalla 2020-02-03 a la(s) 14 52 24](https://user-images.githubusercontent.com/60626488/73689863-d4f2af80-4694-11ea-9b30-5f99405ae351.png)

This is not affecting the functionality but is needed for accessibility goals. 

To fix this we just need to add a property on the cvmodal and the cvnotification components to be passed as the aria-label for the close ‘X’ button

**Steps to reproduce the issue:**
1-Make use of the CvModal or CvNotification component.
2-Install an accessibility check tool.
3-Analyze

**Comment by lee-chase** [comment]
Note CvToastNotification and CvInlineNotification already have closeAriaLabel properties which are shown on all but default stories.
