### ISSUE TITLE
CvPagination listens for input events on cv-select for "page number" and "no of items" which is not working on IE 11 and IE Edge

### ISSUE THREAD

**Issue by sadmard** [carbon-design-system/carbon-components-vue#821]
The fix for issue #720 which I opened last year is not complete. 
It only fixed the cv-select to emit "change" event but cv-pagination is still only listening for "input" events on cv-select. 
So pagination is still not reacting on select changes on IE 11 and IE Edge.

**Comment by sadmard** [comment]
@lee-chase Thanks for fixing, when will next release with this fix be available?

**Comment by lee-chase** [comment]
@sadmard I will make a canary today. If it works for you then will make a non-canary release tomorrow.

**Comment by sadmard** [comment]
@lee-chase Thanks, the canary is working for me. I have opened another regression issue with CvDataTable column headers #825. As we are approaching our release it would be great if you can take a look and include a fix before making a new non-canary release.
