### ISSUE TITLE
Regression: CvDataTable ignores column headingStyles

### ISSUE THREAD

**Issue by sadmard** [carbon-design-system/carbon-components-vue#825]
After upgrading from @carbon/vue 2.18.0 to 2.21.0 the CvDataTable headingStyle property for columns is ignored.

Check the sample on http://vue.carbondesignsystem.com/?path=/story/components-cvdatatable--styled-columns. The column headers should be uppercase but they aren't.

**Comment by lee-chase** [comment]
Not fixed. Adding sort sill removes styling.
