### ISSUE TITLE
Accordion @change event not firing

### ISSUE THREAD

**Issue by JosephAustin** [carbon-design-system/carbon-components-vue#830]
## Change event never fires for the accordion component

Despite it appearing to work in the storyboard, directly implementing the same functionality doesn't seem to work. As a result, cannot get the thing to only open one item at a time.

## Detailed description

- I'm using simple Vue built from vue-cli 4.1.2
- "carbon-components-vue": "0.0.1" seems to be the one npm installs
- npm is 6.9.0

## Steps to reproduce the issue

1. Simple template
```
<cv-accordion @change="optionChanged" ref="acc">
            <cv-accordion-item :open="optionOpen[0]">
             ....
```
2. Script has needed data
```
  data () {
    return {
      optionOpen: [false, false]
    }
  },
```
3. Used same function shown in storyboard
```
    optionChanged(ev) {
      this.optionOpen= this.$refs.acc.state.map((item, index) => index === ev.changedIndex)
    }
```
4. Nothing happens. Toggling does expand/flatten but the event never seems to come in. Tried altering @change to a simple alert and it did not work. 

## Ideas

It could be a problem in web pack but it shouldn't be. Inspecting the code, accordion should recieve a cv:change event from the individual items. Copying cv-accordion.vue to my own project and renaming that for use resulted in the same problem. The cv:change event never seems to come through. Potentially, the forced typing of boolean is getting hung up somewhere on a 1:0 value instead. As you can see though, I clearly used booleans.

**Comment by lee-chase** [comment]
Does this help or can you make it go wrong?
https://codepen.io/lee-chase/pen/yLNBGRN

**Comment by lee-chase** [comment]
Closing, presumed resolved.
