### ISSUE TITLE
Pagination will stalled the page when “count” is a large number。

### ISSUE THREAD

**Issue by MurlinGao** [carbon-design-system/carbon-components-vue#831]
when count is large than 10000，this bug will show out。

**Comment by lee-chase** [comment]
This is really just the browser hanging when we try and render thousands of option elements.

Chrome, Opera and Mozilla limited this to 10000 according to https://chromium.googlesource.com/chromium/blink.git/+/master/Source/core/html/HTMLSelectElement.cpp#77

Will raise an issue with CarbonDesign, to determine a better solution.

As a workaround do not specify the number of items e.g.

https://codepen.io/lee-chase/pen/5f2b6bae52d8cd9111e6a5ef258a0840
