### ISSUE TITLE
Batch select checkboxes in CvDataTable have DAP violations

### ISSUE THREAD

**Issue by sadmard** [carbon-design-system/carbon-components-vue#832]
DAP violation: Form control element input is missing associated label
See Storyboard http://vue.carbondesignsystem.com/?path=/story/components-cvdatatable--default with DAP enabled.

We encountered the same problem when using CvCheckbox without a label in our application because we cannot add an aria-label to CvCheckbox.

**Comment by lee-chase** [comment]
@sadmard  let me know if that works for you canary just published.
