### ISSUE TITLE
CvCheckbox without label has DAP violations

### ISSUE THREAD

**Issue by sadmard** [carbon-design-system/carbon-components-vue#835]
We are using CvCheckbox in a CvDataTable component similar to batch actions and we get the following DAP violations because we are not using the label property for the CvCheckbox:
`LABEL element is missing descriptive text that identifies the expected input.`

I would expect no label tag if no label is specified for the checkbox. 
For accessibility either label or aria-label must be specified for CvCheckbox.

**Comment by lee-chase** [comment]
@sadmard let me know if that works for you canary just published.
