### ISSUE TITLE
CvDataTable batch actions should not prevent from searching the table

### ISSUE THREAD

**Issue by sabinead2** [carbon-design-system/carbon-components-vue#847]
**Is your feature request related to a problem? Please describe.**
As soon as I select one item in the data table I can no longer search the data table to find other items to select.

**Describe the solution you'd like**
I'd like to be able to search even if I have already selected items.

**Describe alternatives you've considered**
As an alternative we have implemented batch selection on our own.

**Comment by lee-chase** [comment]
Thanks for the suggestion. As this differs from the current UX for the Carbon Design System I have passed the request onto that team for consideration.
