### ISSUE TITLE
CvDataTable: Search text overlaps with search close button

### ISSUE THREAD

**Issue by sabinead2** [carbon-design-system/carbon-components-vue#848]
If the entered search text is longer than the space available the x close button overlays the search text

![image](https://user-images.githubusercontent.com/50632387/75777131-b0522c00-5d55-11ea-8a72-96e9dd4d1936.png)

As a work-around for our data tables we are using
```
/deep/ .bx--toolbar-search-container-active .bx--search .bx--search-input {
  padding-right: 3rem;
}

```

**Comment by lee-chase** [comment]
This looks as though it is just a matter of updating to the latest CSS.

**Comment by sabinead** [comment]
Right, after our latest update the issue is fixed.
