### ISSUE TITLE
CvDataTable search field has rendering problems in IE11

### ISSUE THREAD

**Issue by KJaspers** [carbon-design-system/carbon-components-vue#856]
We found some rendering problems for the CvDataTable in IE11.
Used @carbon/vue version: 2.23.0
See screenshots below:

Initial view -> clear button not visible:
<img width="1177" alt="Screenshot 2020-03-23 at 08 10 41" src="https://user-images.githubusercontent.com/50624181/77291063-cf513780-6cdd-11ea-9839-da5c99018597.png">

Click the clear button -> search field and refresh button are cropped:
<img width="1221" alt="Screenshot 2020-03-23 at 08 11 43" src="https://user-images.githubusercontent.com/50624181/77291171-fc9de580-6cdd-11ea-8c36-b7fcf31c917c.png">

**Comment by lee-chase** [comment]
@KJaspers could you create a sample I can try on IE11. Currently this does not work at all for me https://github.com/lee-chase/carbon-vue-sample/tree/TableSample

Please deploy to a forked repo's gh-pages
