### ISSUE TITLE
CvDropdown required two tabs presses to cycle focus past the component.

### ISSUE THREAD

**Issue by william-glasse** [carbon-design-system/carbon-components-vue#867]
## Detailed description

> Describe in detail the issue you're having.

For accessibility reasons, I believe to tab through this item should only require a single tab.

> Is this issue related to a specific component?

CvDropdown

> What browser are you working in?

chrome

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

## Steps to reproduce the issue

1. Visit component here http://vue.carbondesignsystem.com/?path=/story/components-cvdropdown--default
2. Try tab cycling through, focus remains on the dropdown for two tab presses.

## Additional information

This can be fixed I believe by removing the tabindex=0 from the parent, since the sub-component button is also focusable. 

- Screenshots or code
- Notes

**Comment by lee-chase** [comment]
You are correct, it would appear to be an overhang from the DOM changes made when moving to 10_6. Feel free to submit a PR. Otherwise, I'll try and update this tomorrow.

**Comment by william-glasse** [comment]
@lee-chase, I'm super keen to begin contributing to this project, this seems like a simple one for me to attack. This seems a good candidate for a junior dev such as myself (can be daunting getting started in a new project), hopefully, I will find the time this afternoon to have a look!

**Comment by lee-chase** [comment]
Fixed by #868
