### ISSUE TITLE
CvMultiSelect: tag inside cvmultiselect has wrong colour on v10.11.0

### ISSUE THREAD

**Issue by mrsideshowjack** [carbon-design-system/carbon-components-vue#871]
## What package(s) are you using?

- [x] `carbon-components`
- [x] `carbon-components-vue`

## Detailed description

> Describe in detail the issue you're having.

The tag inside the Multi is a different colour to what is was before.

> Is this issue related to a specific component?

`CvMultiSelect`

> What did you expect to happen? What happened instead? What would you like to
> see changed?

expecting the tag to be `#393939` but it's `#E0E0E0`

> What browser are you working in?

Chrome

> What version of the Carbon Design System are you using?

`v10.11.0`

## Steps to reproduce the issue

1. Select an item from the dropdown

## Additional information

![Screenshot 2020-04-21 at 16 35 50](https://user-images.githubusercontent.com/9937136/79885123-2d149480-83ee-11ea-9295-14d3eba90def.png)

> - React (not present):
>   https://codesandbox.io/s/multiselect-lib5t

> - Vue:
>  https://codesandbox.io/s/carbonvue-multi-select-tag-issue-p69vj?file=/src/App.vue

**Comment by mrsideshowjack** [comment]
Different but related issue, the dropdown doesn't work on `v10.11.1` :/

**Comment by janhassel** [comment]
Side note: the necessary styles will be added with with https://github.com/carbon-design-system/carbon/pull/5910

**Comment by lee-chase** [comment]
While we try to keep in step with the carbon components releases, updates are not always in sync.

I'll create tag for update issues. @mrsideshowjack please create a separate issue noting v10.11 in the title.

**Comment by lee-chase** [comment]
Corrected in current canary.
