### ISSUE TITLE
Showing blank white screen in Microsoft Edge (v44.18362.x) and Internet Explorer (v11.719.x)

### ISSUE THREAD

**Issue by abhay-osizone** [carbon-design-system/carbon-components-vue#892]
I have facing some issue on **Microsoft Edge (v44.18362.x)** and **Internet Explorer (v11.719.x)**.
I have getting blank white screen on both browser with console error in -

**Microsoft Edge** : **`SCRIPT1028: SCRIPT1028: Expected identifier, string or number`**
**Internet Explorer** : **`SCRIPT1003: Expected ':' chunk-vendors.js (5435,1)`**

You can check my project [Project URL](https://educarechat-4b7f3.web.app/)

Also getting blank white screen on both browser while i open official vue sample app from carbon design tutorial section https://vue-step-6--carbon-tutorial-vue.netlify.app/#/

**Comment by lee-chase** [comment]
Really difficult to know what is happening here in built code @abhay-osizone. Are you able to run in debug?

I suspect this will come down to using a babel configuration that works for IE.

Alternatively, update to the latest Edge.

**Comment by abhay-osizone** [comment]
Thanks!
After upgrading to chromium based Edge, it's working fine.
