### ISSUE TITLE
Nested table support for 

### ISSUE THREAD

**Issue by lluvia66** [carbon-design-system/carbon-components-vue#894]
**Is your feature request related to a problem? Please describe.**
We are very eager to hope that Carbon vue can support nested table since our whole design are in this style

**Describe the solution you'd like**
Each row in data table is one childData table, one example attached below.
<img width="1520" alt="nested table" src="https://user-images.githubusercontent.com/40225262/81400470-c5857580-915f-11ea-85ac-4facb8af32d0.png">

**Comment by asudoh** [comment]
Weighing in; Carbon core does not support nested table from our UX guidance. That said, I suggest your designer talk to our designer to figure out an alternative. Thanks!

**Comment by lee-chase** [comment]
Given the above statement from @asudoh @carbon/vue will not be adding support for nested tables.

Products I have worked on typically navigate between views rather than nesting tables as this negates any future concern over multiple levels of nesting.
