### ISSUE TITLE
Disabled combo box is still operational

### ISSUE THREAD

**Issue by superman566** [carbon-design-system/carbon-components-vue#909]
## Detailed description
Hey,
there's a problem with the combo box in vue. If you disable the combo box and then select a value, The combo box is still working well.

## Additional information
![image](https://user-images.githubusercontent.com/8649164/82825436-3ecbda80-9e79-11ea-92e5-9933384cc32a.png)

the combo-box in carbon-react disable feature is working fine. Only carbon-vue has this issue.

 similar issue:
https://github.com/carbon-design-system/carbon/issues/4048

**Comment by lee-chase** [comment]
Thanks for spotting this @superman566 

Will be fixed in the next release and today's canary
