### ISSUE TITLE
yarn start thrown error while executed

### ISSUE THREAD

**Issue by vzrenggamani** [carbon-design-system/carbon-components-vue#910]
## Detailed description

> Describe in detail the issue you're having.

Trying to run a local server of carbon components vue storybook using yarn but the yarn won't execute correctly.

> Is this a feature request (new component, new icon), a bug, or a general issue?

Just general issues

> Is this issue related to a specific component?

No, Just for the storybook.

> What did you expect to happen? What happened instead? What would you like to see changed?

I expect the storybook server comes up and can be used locally.

> What browser are you working in?

Chrome Dev 81

> What version of the Carbon Design System are you using?

`master` branch commit a77677006f4d776d4a089bd52703d56e20896abd

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

No.

## Steps to reproduce the issue

1. Clone the repos with `--depth=1` parameters
2. Run the `yarn` commands
3. execute the `yarn start`
4. Console thrown :
```
C:\Users\hi\GitHub\carbon-components-vue>yarn build:storybook
yarn run v1.22.4
$ yarn info @carbon/vue --json > package-info.jsonl; vue-cli-service storybook:build -c storybook/.storybook -o storybook/storybook-static
{"type":"error","data":"Too many arguments, maximum of 2."}
Done in 0.89s.
```

## Additional information

- Screenshots or code
![image](https://user-images.githubusercontent.com/14950309/82923278-ed206e80-9fa4-11ea-892c-94545818afbe.png)

### System Configuration
OS : Windows 10 Pro v1909 b18363
NodeJS : v12.16.3
yarn : 1.22.4
git : git version 2.26.2.windows.1

**Comment by lee-chase** [comment]
I don't currently have access to a windows setup, so could do with your help debugging this.

If you edit package.json and replace
```
"start": "yarn info @carbon/vue --json > package-info.jsonl; vue-cli-service storybook:serve -p 9001 -c storybook/.storybook",
```

with

```
    "start:a": "yarn info @carbon/vue --json > package-info.jsonl;",
    "start:b": "vue-cli-service storybook:serve -p 9001 -c storybook/.storybook",
```

Execute start:a then start:b and post the results here.

**Comment by vzrenggamani** [comment]
It works like a charm even i don't use `"yarn info @carbon/vue --json > package-info.jsonl;"`.
I am just directly run the app with `"vue-cli-service storybook:serve -p 9001 -c storybook/.storybook"`
