### ISSUE TITLE
[CvPagination]: dropdown icon showing the browser icon

### ISSUE THREAD

**Issue by rafaelmaiach** [carbon-design-system/carbon-components-vue#911]
[CvPagination]: dropdown icon showing the browser icon

## Detailed description
The CvPagination is showing the carbon arrow icon but is showing the default browser icon too like shown in the image below:

![image](https://user-images.githubusercontent.com/13542718/82937270-3f8e6a80-9f66-11ea-9c11-4e25c5f94133.png)

> What browser are you working in?
Chrome

> What version of the Carbon Design System are you using?
"@carbon/elements": "10.12.0",
"@carbon/icons-vue": "10.11.0",
"@carbon/vue": "2.25.1",
"carbon-components": "10.12.0"

**Comment by lee-chase** [comment]
That looks like a number input icon, but there is no number input component in pagination currently.

Can you make this codepen go wrong and specify in which browser

https://codepen.io/lee-chase/pen/PoPvOre

**Comment by rafaelmaiach** [comment]
Hi @lee-chase 
I don't know how to reproduce it, but I noticed that on your codepen, the
```
<select id="uid-a0064d2d-cb64-4ca4-b548-d260b90a7e17" class="bx--select-input">
```
has the `-webkit-appearance: none` set.

But, on my side, for some reason, the  `-webkit-appearance` it hasn't set. It uses only the `appearance: none`, but only this, shows a warning at chrome dev tools style list and don't work.

**Comment by rafaelmaiach** [comment]
I found the problem.
We overrode the `.postcss.json` and didnt include autoprefixer.

![image](https://user-images.githubusercontent.com/13542718/83018953-8b8bee80-9ffc-11ea-8e64-ad4fdb1d075c.png)

now it's working

**Comment by lee-chase** [comment]
That's great, I'll close this issue.
