### ISSUE TITLE
[CvDatePicker]: Bad experience and some bugs

### ISSUE THREAD

**Issue by rafaelmaiach** [carbon-design-system/carbon-components-vue#921]
## Detailed description
1) Vue Carbon on Storybook isn't working as the library implementation.
On Storybook:
![image](https://user-images.githubusercontent.com/13542718/84518696-77581a80-aca7-11ea-8f31-3fa3e0a55f8b.png)

On Code:
![image](https://user-images.githubusercontent.com/13542718/84518754-8b9c1780-aca7-11ea-8ea1-cddeb2b6f69b.png)
![image](https://user-images.githubusercontent.com/13542718/84518780-935bbc00-aca7-11ea-9605-e2ca95250a6d.png)

2) I can't reach Month and Year fields using keyboard. I don't know if I'm not using the correct keys, but I tried with TAB and Arrow Keys and I couldn't reach them, only the days. And I don't know if this is the desired behavior. I can press the up arrow key to keep passing through months and even years after some presses. How does the accessibility work in these cases? 

3) I set the maxDate to the current day, but after selecting a date, the visual information about the days that are disabled, just disappear.
![image](https://user-images.githubusercontent.com/13542718/84519260-390f2b00-aca8-11ea-8140-2a7086b867ae.png)
![image](https://user-images.githubusercontent.com/13542718/84519271-3e6c7580-aca8-11ea-82d9-cccddce741f0.png)

> Is this a feature request (new component, new icon), a bug, or a general issue?

Bug

> Is this issue related to a specific component?

CvDatePicker

> What did you expect to happen? What happened instead? What would you like to see changed?

Storybook and library working equally.
An explanation or fix on the accessibility
The disabled days keep showing even when a date is selected

> What browser are you working in?

Version 83.0.4103.97 (Official Build) (64-bit)

> What version of the Carbon Design System are you using?

"@carbon/elements": "10.12.0",
"@carbon/icons-vue": "10.11.0",
"@carbon/vue": "2.25.1",
"carbon-components": "10.12.0",

## Steps to reproduce the issue

1. Pass "new Date()" as the value for CvDatePicker
2. Try to use keyboard on the DatePicker
3. Disabled days should keep the visual appearance even if a date is selected

**Comment by lee-chase** [comment]
1. Fixed with PR #1031
2. You are correct and this needs raising as an issue to core carbon.  Given the conclusion of https://github.com/carbon-design-system/carbon/issues/5572 I would expect it to be resolved in the redesign.
3. Unable to reproduce may have been fixed by flatpikr updates.
