### ISSUE TITLE
cv-button icon svg not display

### ISSUE THREAD

**Issue by MwSpaceLLC** [carbon-design-system/carbon-components-vue#925]
Hi there, for us svg icon not work.

![image](https://user-images.githubusercontent.com/29952045/84690258-78f13f00-af42-11ea-9813-dfe95f4d8805.png)

![image](https://user-images.githubusercontent.com/29952045/84690271-81497a00-af42-11ea-98a6-4049990a4fed.png)

![image](https://user-images.githubusercontent.com/29952045/84690303-94f4e080-af42-11ea-95ed-276c45f298fe.png)

**Comment by selimdoyranli** [comment]
Try this
```
<cv-button kind="primary" size="field">
  <span>Register</span>
  <Registration16 class="bx--btn__icon"></Registration16>
</cv-button>
```
and i'm using @carbon/icons-vue package

**Comment by lee-chase** [comment]
In order to add an icon using a path you need to use webpack or similar to load the icon path

e.g. 
```js
const exampleIconPath = require('../../packages/core/src/assets/images/example-icons.svg');
```

You can then use this as follows

```html
<cv-button :icon="exampleIconPath"
```

Assuming you have done this please create a codepen or codesandbox replicating this issue.

Alternatively use a carbon icon as suggested by @selimdoyranli

**Comment by MwSpaceLLC** [comment]
Sorry for reply delay. 

We have changed from vue to react for better experience 😁

**Comment by lee-chase** [comment]
Thanks. For anyone looking at this in future the icon as a path part currently expects a path to an SVG symbol not raw SVG or a non-symbol SVG.
