### ISSUE TITLE
Is CvTextInput autofocus/focus disabled?

### ISSUE THREAD

**Issue by jungleBadger** [carbon-design-system/carbon-components-vue#926]
## Summary

Is the `autofocus` directive ignored on `cv-text-input` elements?

## Relevant information

I'm building a feature that upon a button click, a new row would be added, each row contains two text input fields.

I've been trying, what would be expected to be intuitively easy, add the `autofocus`, and no good.

I even created a small directive to see if it would do the trick, but no good as well.

```js
	Vue.directive("focus", {
		inserted(el) {
			el.focus();
		}
	});
```

So, I wonder if the focus on CvTextInputs are disabled for some design reason, or if it is a bug.

**Comment by lee-chase** [comment]
No, but the focus will need to go to the text input not the wrapping element. Perhaps a focus method could be added to achieve this.

**Comment by lee-chase** [comment]
Added https://github.com/carbon-design-system/carbon-components-vue/issues/930 will make CvTextInput the first one.

**Comment by lee-chase** [comment]
Added focus method to next release.

**Comment by jungleBadger** [comment]
Thanks, @lee-chase! I was willing to make that contribution, but you got that quickly! I appreciate it because this will greatly improve the experience of the feature I'm working on.

Let me know if you need further help with this development.

**Comment by lee-chase** [comment]
There are plenty of other components that could do with the same treatment or having their 'bx's replaced with the carbonPrefix setting ;-)
