### ISSUE TITLE
Progress Bar step labels look like a link tag but nothing happens when clicking on it

### ISSUE THREAD

**Issue by KJaspers** [carbon-design-system/carbon-components-vue#937]
This issue was reported to carbon elements and fixed:
https://github.com/carbon-design-system/carbon/issues/5515

However, the problem still exists in carbon vue component. As far as I understand, the idea for vanilla carbon is to have it as a link if a tooltip is specified, so that the tooltip is shown when clicking on it. The carbon vue implementation seems to be different and still shows the link when hovering over the label even if no tooltip is specified.

**Comment by jungleBadger** [comment]
Accepting the `to` and `href` props would be acceptable to achieve that @lee-chase? Let me know and I can work on getting this done.

**Comment by KJaspers** [comment]
Any updates on this one?
