### ISSUE TITLE
cv-icon-button not working with documentation example

### ISSUE THREAD

**Issue by christianlmc** [carbon-design-system/carbon-components-vue#945]
## Summary
Tried to follow the example in https://vue.carbondesignsystem.com/?path=/story/components-cvbutton--icon-only as following:
```
<cv-icon-button
      kind="primary"
      :size="''"
      :disabled="false"
      :icon="iconAlways"
      class="bx--btn bx--btn--icon-only"
/>
```
```js
iconAlways = {
    name: 'Edit16',
    functional: true,
    props: {
      title: {
        type: null
      }
    },
    _Ctor: {}
  }
```
On the browser I got the following error:
![image](https://user-images.githubusercontent.com/24314863/87042962-be63fd80-c1ca-11ea-9830-bae69624631b.png)

Is there an workaround to this, am I doing something wrong?

**Comment by lee-chase** [comment]
The component viewer in trying to be helpful is showing the iconAlways value as you list above. It should however be an icon imported from @carbon-icons/vue or an SVG symbol

```
<cv-icon-button
      kind="primary"
      :size="''"
      :disabled="false"
      :icon="AddFilled16"
      class="bx--btn bx--btn--icon-only"
/>

<script>
import AddFilled16 from '@carbon/icons-vue/es/add--filled/16';

export default {
...
   components: { AddFilled16 }
...
}
```

**Comment by christianlmc** [comment]
That didn't solved my issue, here's the code
```
<cv-button
        kind="primary"
        :size="''"
        :icon="Edit16"
        :disabled="false"
        class="bx--btn bx--btn--icon-only"
      >
        Primary Icon New Test
</cv-button>

<script lang="ts">
import Edit16 from '@carbon/icons-vue/es/edit/16'

@Component({
  components: {
    Edit16
  }
})
```

And the issue:
![image](https://user-images.githubusercontent.com/24314863/87156439-09e1de80-c293-11ea-88fd-7aaca2232fb6.png)

**Comment by lee-chase** [comment]
My apologies, I've just realised the error.

component: { Edit16 }

Is not appropriate when passing a component as a property. Instead, you'll need to add it to the components object.

There are various ways to do this which you can see https://codesandbox.io/s/5zk452o9jp?file=/src/TestComponent.vue:0-728

```html
<template>
  <div>
    <Edit16/>
    <br>
    <br>
    <cv-button>Hello world
      <Edit16/>
    </cv-button>
    <br>
    <br>
    <cv-button :icon="MyEdit16">Hello world</cv-button>

    <br>
    <br>
    <cv-button :icon="anEdit16">Hello world</cv-button>

    <br>
    <br>
    <cv-button :icon="AddFilled16">Hello world</cv-button>
  </div>
</template>

<script>
import Edit16 from "@carbon/icons-vue/es/edit/16";
import AddFilled16 from "@carbon/icons-vue/es/add--filled/16";

export default {
  name: "TestComponent",
  components: { Edit16 },
  created() {
    this.anEdit16 = Edit16;
  },
  data() {
    return {
      AddFilled16
    };
  },
  computed: {
    MyEdit16() {
      return Edit16;
    }
  }
};
</script>
```

**Comment by lee-chase** [comment]
Note the first button does not really work due to classes added as part of the button component.

**Comment by christianlmc** [comment]
Sorry for the late reply. All the examples worked as expected, thank you
