### ISSUE TITLE
cvInlineNotification and cvToastNotification close buttons have blue borders enabled by default

### ISSUE THREAD

**Issue by christianlmc** [carbon-design-system/carbon-components-vue#946]
## Detailed description

> Describe in detail the issue you're having.

All the X'es have a blue border on low-contrast mode
![image](https://user-images.githubusercontent.com/24314863/87067493-8076d180-c1ea-11ea-9fc2-8721f851f915.png)

> Is this a feature request (new component, new icon), a bug, or a general issue?

General Issue

> Is this issue related to a specific component?

cvInlineNotification and cvToastNotification

> What did you expect to happen? What happened instead? What would you like to see changed?

Expected behavior:
![image](https://user-images.githubusercontent.com/24314863/87067804-ecf1d080-c1ea-11ea-9b05-cda5beb0f3fc.png)

> What browser are you working in?

Chrome 81

> What version of the Carbon Design System are you using?

"@carbon/vue": "^2.28.0"

## Steps to reproduce the issue

1. Step one
```
<cv-inline-notification
        title="Inline Notification - Low Contrast"
        sub-title="Subtitulo"
        action-label="Acao"
        :low-contrast="true"
        @close="closeIt"
        @action="closeIt"
/>
```
2. Step two
Go to browser

**Comment by christianlmc** [comment]
Workaround for the issue:
```
<style lang="scss">
.bx--inline-notification--low-contrast .bx--inline-notification__close-button {
  outline: 0px;
  outline-offset: 0px;
}

.bx--toast-notification--low-contrast .bx--toast-notification__close-button {
  outline: 0px;
  outline-offset: 0px;
}
</style>
```

**Comment by lee-chase** [comment]
There is something odd going on that I've not quite figured out. The focus should show on hover is white in all cases on thiscode sandbox.

This does not work https://codesandbox.io/s/carbon-components-vue-j69zk?file=/src/TestComponent.vue:19-96

but the storybook does http://vue.carbondesignsystem.com/?path=/story/components-cvtoastnotification--default

**Comment by mrsideshowjack** [comment]
This should be fixed in newer versions of `carbon-components`

old
https://codesandbox.io/s/carbonvue-notification-btn-qzv6s

new
https://codesandbox.io/s/carbonvue-notification-btn-forked-3ocn5
