### ISSUE TITLE
Add support for `required` and other validation attributes for input fields

### ISSUE THREAD

**Issue by TimonLukas** [carbon-design-system/carbon-components-vue#948]
**Is your feature request related to a problem? Please describe.**
When I build an app with form elements, I try to apply narrow validation rules to give the user easy and direct feedback about their input. Of course any input has to be independently validated on the server, but HTML5 validation attributes (like `required`, `min-length` etc.) give an easy and direct way to add client-side validation. Currently there is no way to pass these attributes to the input elements inside e. g. a `cv-text-input` or a `cv-time-picker`.

**Describe the solution you'd like**
It would be nice to add pass-through attribute support using `v-bind="$attrs"` on the input elements. This would allow developers to specify any valid input element attribute (like validation attributes) without making the component code itself more complicated.

**Describe alternatives you've considered**
It would be possible to instead implement a manual prop-based interface for this, but that would be a lot of extra work with little to no pay-off.

**Comment by lee-chase** [comment]
$attrs is already bound to the input for cv-text-input and textarea for cv-text-area.

**Comment by TimonLukas** [comment]
Whoops, not sure how I overlooked that. Very nice, thank you!
