### ISSUE TITLE
cv-file-uploader from vue is different compared to the one on carbondesignsystem.com

### ISSUE THREAD

**Issue by christianlmc** [carbon-design-system/carbon-components-vue#949]
## Summary

Tried to use the cv-file-uploader and when I added the component in I got the following
![image](https://user-images.githubusercontent.com/24314863/87676755-5fb0fd80-c74f-11ea-9a43-cb1a295908cc.png)

Looking at the docs https://www.carbondesignsystem.com/components/file-uploader/code/, I wanted to achieve the following result:
![image](https://user-images.githubusercontent.com/24314863/87677013-a999e380-c74f-11ea-9486-bb4b09a743a9.png)

Is there a way to do it?

**Comment by lee-chase** [comment]
Not at the moment. This appears to be a new feature in Carbon 10 (existed in V9).

Both https://react.carbondesignsystem.com/?path=/story/fileuploader--fileuploaderbutton and https://react.carbondesignsystem.com/?path=/story/fileuploader--fileuploader are missing.

**Comment by lee-chase** [comment]
Canary published shortly should resolve this. It does not add the fileuploaderbutton
