### ISSUE TITLE
[CvMultiSelect] - Label is covered when using the 'filterable' option, even though there is space available

### ISSUE THREAD

**Issue by william-glasse** [carbon-design-system/carbon-components-vue#955]
## Detailed description

> Describe in detail the issue you're having.

When using the CvMultiSelect component with the "filterable" option, when the multi select has a width which is less than the label length, the dropdown covers part of the label, even though there is available space for the label. This behaviour does not occur without the filterable option.

> Is this a feature request (new component, new icon), a bug, or a general issue?

bug

> Is this issue related to a specific component?

CvMultiSelect

> What did you expect to happen? What happened instead? What would you like to see changed?

I'd expect the dropdown button to only take the space it needs, rather than covering up the label. 

> What browser are you working in?

Chrome

> What version of the Carbon Design System are you using?

carbon vue - 2.29.0
carbon components - 10.16.0

## Steps to reproduce the issue

1. Step one - visit https://codesandbox.io/s/carbonvue-multiselect-issue-filterable-88lw9?file=/src/App.vue
2. Step two - Observe that when the multiselect is subject to small widths, the label is covered despite there being available space.
3. Step three - Observe that the behaviour doesn't occur for the second example, whereby the filterable option is false.

## Additional information

- Screenshots or code
![Screenshot 2020-07-23 at 14 16 07](https://user-images.githubusercontent.com/56296356/88290696-12083800-ccef-11ea-9455-002040ed7cfe.png)
The above screenshot shows the same CvMultiSelect, with the first being a "filterable" type.

**Comment by mrsideshowjack** [comment]
Issue seems fixed in newer versions of @carbon/vue

**Comment by davidnixon** [comment]
Working in Vue 3 as well
