### ISSUE TITLE
Date-picker can not be updated by set 'v-model', 'value' or 'dataValue' through '$refs'

### ISSUE THREAD

**Issue by gengengengengen** [carbon-design-system/carbon-components-vue#969]
In my application, I want to set date-picker to a valid date when validation failed. The date is a member of a object and bind to 'v-model' (object = { date: 'value', ... }).

I tried to set the 'object.date' directly, set '$refs.datePicker.value' or 'dataValue', the actual value is updated, but all of them did not trigger the updating the value shown on the calendar and input field. 

To force the component update, I also tried `$set(obj, memberKey, value)` but did not work either.

Is there any way to update this component?

**Comment by lee-chase** [comment]
Can you post code showing this?

Perhaps update this https://codesandbox.io/s/carbon-components-vue-b0hnt?file=/src/TestComponent.vue

If you are attempting to update the value during an event e.g. @change then you may find it is a timing issue. Try using this.$nextTick() to wrap your value update.

**Comment by gengengengengen** [comment]
> Can you post code showing this?
> 
> Perhaps update this https://codesandbox.io/s/carbon-components-vue-b0hnt?file=/src/TestComponent.vue
> 
> If you are attempting to update the value during an event e.g. @change then you may find it is a timing issue. Try using this.$nextTick() to wrap your value update.

@lee-chase Thank you very much. this.$nextTick() works for me. Issue fixed when i put `this.obj.val = oldVal` into the callback of this.$nextTick().Thank you.

And this is my failed code: 
```
<template>
  <div>
    <cv-date-picker v-model="obj.val" kind="single" :calOptions="calOptions"/>
    <br>
    <cv-text-input v-model="obj.val"/>
    <br>
    <cv-button>Set date</cv-button>
  </div>
</template>

<script>
import Edit16 from "@carbon/icons-vue/es/edit/16";
import AddFilled16 from "@carbon/icons-vue/es/add--filled/16";
import { CvDatePicker, CvButton, CvTextInput } from "@carbon/vue/";

export default {
  name: "TestComponent",
  components: { Edit16, CvButton, CvDatePicker, CvTextInput },
  created() {
    this.anEdit16 = Edit16;
  },
  data() {
    return {
      AddFilled16,
      obj: {val: "31/12/2011"},
      calOptions: {
        dateFormat: "d/m/Y"
      }
    };
  },
  computed: {
    MyEdit16() {
      return Edit16;
    }
  },
  watch: {
    "obj.val": function(newVal, oldVal){
      // some datetime check
      if(.............) {
        this.obj.val = oldVal
      }
    }
  }
};
</script>

<style scoped>
.green {
  color: green;
}
</style>

```
