### ISSUE TITLE
cv file uploader does not work with submit

### ISSUE THREAD

**Issue by fedorzajac** [carbon-design-system/carbon-components-vue#981]
As per discussion with @lee-chase:

cv file uploader does not work for me when used as regular form behavior

 in plain html, when I click submit button, the file gets uploaded in automated fashion via browser and it is stored in temporary space somewhere and I can access the temporary file by temporary filename and can read it from backend. what shold I send in axios request to get the same resul and ‘accesible’ path name to access the uploaded file content?

I was not able to mimic this behavior.

technologies:

Vue cdn + ruby sinatra at back end.

**Comment by davidnixon** [comment]
Please try with Vue 3 component
