### ISSUE TITLE
Drop-down menu can not move back automatically after the mouse click other area

### ISSUE THREAD

**Issue by lluvia66** [carbon-design-system/carbon-components-vue#983]
The drop-down menu can not move back automatically after the mouse click other area in the new version. The url in storybook is : vue.carbondesignsystem.com/?path=/story/components-cvdropdown--default (by the way, the example in carbon design home page can move back)Thank you.

**Comment by lee-chase** [comment]
You can make it move back e.g. https://codesandbox.io/s/carbonvue-cv-dropdown-zil8c?file=/src/App.vue but controls do not typically grab focus after focusout.
